package com.tempus.gss.product.tra.dao;

import com.tempus.gss.product.tra.api.entity.TraSaleChangeDetail;
import com.tempus.gss.product.tra.api.entity.TraSaleChangeDetailExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface TraSaleChangeDetailDao {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TRA_SALE_CHANGE_DETAIL
     *
     * @mbggenerated Fri Feb 24 15:34:26 CST 2017
     */
    int countByExample(TraSaleChangeDetailExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TRA_SALE_CHANGE_DETAIL
     *
     * @mbggenerated Fri Feb 24 15:34:26 CST 2017
     */
    int deleteByExample(TraSaleChangeDetailExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TRA_SALE_CHANGE_DETAIL
     *
     * @mbggenerated Fri Feb 24 15:34:26 CST 2017
     */
    int deleteByPrimaryKey(Long saleChangeDetailNo);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TRA_SALE_CHANGE_DETAIL
     *
     * @mbggenerated Fri Feb 24 15:34:26 CST 2017
     */
    int insert(TraSaleChangeDetail record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TRA_SALE_CHANGE_DETAIL
     *
     * @mbggenerated Fri Feb 24 15:34:26 CST 2017
     */
    int insertSelective(TraSaleChangeDetail record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TRA_SALE_CHANGE_DETAIL
     *
     * @mbggenerated Fri Feb 24 15:34:26 CST 2017
     */
    List<TraSaleChangeDetail> selectByExample(TraSaleChangeDetailExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TRA_SALE_CHANGE_DETAIL
     *
     * @mbggenerated Fri Feb 24 15:34:26 CST 2017
     */
    TraSaleChangeDetail selectByPrimaryKey(Long saleChangeDetailNo);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TRA_SALE_CHANGE_DETAIL
     *
     * @mbggenerated Fri Feb 24 15:34:26 CST 2017
     */
    int updateByExampleSelective(@Param("record") TraSaleChangeDetail record, @Param("example") TraSaleChangeDetailExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TRA_SALE_CHANGE_DETAIL
     *
     * @mbggenerated Fri Feb 24 15:34:26 CST 2017
     */
    int updateByExample(@Param("record") TraSaleChangeDetail record, @Param("example") TraSaleChangeDetailExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TRA_SALE_CHANGE_DETAIL
     *
     * @mbggenerated Fri Feb 24 15:34:26 CST 2017
     */
    int updateByPrimaryKeySelective(TraSaleChangeDetail record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TRA_SALE_CHANGE_DETAIL
     *
     * @mbggenerated Fri Feb 24 15:34:26 CST 2017
     */
    int updateByPrimaryKey(TraSaleChangeDetail record);
    
    List<TraSaleChangeDetail> selectBySaleChangeNo(Long saleChangeNo);
}