package com.tempus.gss.product.tra.dao;

import com.tempus.gss.product.tra.api.entity.TraSaleOrderDetail;
import com.tempus.gss.product.tra.api.entity.TraSaleOrderDetailExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface TraSaleOrderDetailDao {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TRA_SALE_ORDER_DETAIL
     *
     * @mbggenerated Mon Feb 27 15:21:11 CST 2017
     */
    int countByExample(TraSaleOrderDetailExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TRA_SALE_ORDER_DETAIL
     *
     * @mbggenerated Mon Feb 27 15:21:11 CST 2017
     */
    int deleteByExample(TraSaleOrderDetailExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TRA_SALE_ORDER_DETAIL
     *
     * @mbggenerated Mon Feb 27 15:21:11 CST 2017
     */
    int deleteByPrimaryKey(Long saleOrderDetailNo);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TRA_SALE_ORDER_DETAIL
     *
     * @mbggenerated Mon Feb 27 15:21:11 CST 2017
     */
    int insert(TraSaleOrderDetail record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TRA_SALE_ORDER_DETAIL
     *
     * @mbggenerated Mon Feb 27 15:21:11 CST 2017
     */
    int insertSelective(TraSaleOrderDetail record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TRA_SALE_ORDER_DETAIL
     *
     * @mbggenerated Mon Feb 27 15:21:11 CST 2017
     */
    List<TraSaleOrderDetail> selectByExample(TraSaleOrderDetailExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TRA_SALE_ORDER_DETAIL
     *
     * @mbggenerated Mon Feb 27 15:21:11 CST 2017
     */
    TraSaleOrderDetail selectByPrimaryKey(Long saleOrderDetailNo);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TRA_SALE_ORDER_DETAIL
     *
     * @mbggenerated Mon Feb 27 15:21:11 CST 2017
     */
    int updateByExampleSelective(@Param("record") TraSaleOrderDetail record, @Param("example") TraSaleOrderDetailExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TRA_SALE_ORDER_DETAIL
     *
     * @mbggenerated Mon Feb 27 15:21:11 CST 2017
     */
    int updateByExample(@Param("record") TraSaleOrderDetail record, @Param("example") TraSaleOrderDetailExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TRA_SALE_ORDER_DETAIL
     *
     * @mbggenerated Mon Feb 27 15:21:11 CST 2017
     */
    int updateByPrimaryKeySelective(TraSaleOrderDetail record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TRA_SALE_ORDER_DETAIL
     *
     * @mbggenerated Mon Feb 27 15:21:11 CST 2017
     */
    int updateByPrimaryKey(TraSaleOrderDetail record);
    
    /*
	* 根据销售编号查询销售单明细
	* */
	List<TraSaleOrderDetail>  selectBySaleOrderNo(Long saleOrderNo);
}