package com.tempus.gss.product.tra.dao;

import com.baomidou.mybatisplus.plugins.Page;
import com.tempus.gss.product.tra.api.entity.TraSaleOrderExt;
import com.tempus.gss.product.tra.api.entity.TraSaleOrderExtExample;
import java.util.List;

import com.tempus.gss.product.tra.api.entity.vo.TraSaleOrderExtVo;
import org.apache.ibatis.annotations.Param;

public interface TraSaleOrderExtDao {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TRA_SALE_ORDER_EXT
     *
     * @mbggenerated Sat Feb 25 17:24:56 CST 2017
     */
    int countByExample(TraSaleOrderExtExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TRA_SALE_ORDER_EXT
     *
     * @mbggenerated Sat Feb 25 17:24:56 CST 2017
     */
    int deleteByExample(TraSaleOrderExtExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TRA_SALE_ORDER_EXT
     *
     * @mbggenerated Sat Feb 25 17:24:56 CST 2017
     */
    int deleteByPrimaryKey(Long saleOrderNo);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TRA_SALE_ORDER_EXT
     *
     * @mbggenerated Sat Feb 25 17:24:56 CST 2017
     */
    int insert(TraSaleOrderExt record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TRA_SALE_ORDER_EXT
     *
     * @mbggenerated Sat Feb 25 17:24:56 CST 2017
     */
    int insertSelective(TraSaleOrderExt record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TRA_SALE_ORDER_EXT
     *
     * @mbggenerated Sat Feb 25 17:24:56 CST 2017
     */
    List<TraSaleOrderExt> selectByExample(TraSaleOrderExtExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TRA_SALE_ORDER_EXT
     *
     * @mbggenerated Sat Feb 25 17:24:56 CST 2017
     */
    TraSaleOrderExt selectByPrimaryKey(Long saleOrderNo);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TRA_SALE_ORDER_EXT
     *
     * @mbggenerated Sat Feb 25 17:24:56 CST 2017
     */
    int updateByExampleSelective(@Param("record") TraSaleOrderExt record, @Param("example") TraSaleOrderExtExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TRA_SALE_ORDER_EXT
     *
     * @mbggenerated Sat Feb 25 17:24:56 CST 2017
     */
    int updateByExample(@Param("record") TraSaleOrderExt record, @Param("example") TraSaleOrderExtExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TRA_SALE_ORDER_EXT
     *
     * @mbggenerated Sat Feb 25 17:24:56 CST 2017
     */
    int updateByPrimaryKeySelective(TraSaleOrderExt record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TRA_SALE_ORDER_EXT
     *
     * @mbggenerated Sat Feb 25 17:24:56 CST 2017
     */
    int updateByPrimaryKey(TraSaleOrderExt record);

    List<TraSaleOrderExt> queryObjByKey(Page<TraSaleOrderExt> page, TraSaleOrderExtVo entity);
    
    TraSaleOrderExt queryByBuyOrderNo(Long buyOrderNo);
}