package com.tempus.gss.product.tra.dao;

import java.util.List;

import org.apache.ibatis.annotations.Param;

import com.baomidou.mybatisplus.plugins.Page;
import com.tempus.gss.product.tra.api.entity.TraSaleChangeExt;
import com.tempus.gss.product.tra.api.entity.TraSaleChangeExtExample;
import com.tempus.gss.product.tra.api.entity.vo.TraSaleChangeExtVo;

public interface TraSaleChangeExtDao {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TRA_SALE_CHANGE_EXT
     *
     * @mbggenerated Fri Feb 24 15:34:26 CST 2017
     */
    int countByExample(TraSaleChangeExtExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TRA_SALE_CHANGE_EXT
     *
     * @mbggenerated Fri Feb 24 15:34:26 CST 2017
     */
    int deleteByExample(TraSaleChangeExtExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TRA_SALE_CHANGE_EXT
     *
     * @mbggenerated Fri Feb 24 15:34:26 CST 2017
     */
    int deleteByPrimaryKey(Long saleChangeNo);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TRA_SALE_CHANGE_EXT
     *
     * @mbggenerated Fri Feb 24 15:34:26 CST 2017
     */
    int insert(TraSaleChangeExt record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TRA_SALE_CHANGE_EXT
     *
     * @mbggenerated Fri Feb 24 15:34:26 CST 2017
     */
    int insertSelective(TraSaleChangeExt record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TRA_SALE_CHANGE_EXT
     *
     * @mbggenerated Fri Feb 24 15:34:26 CST 2017
     */
    List<TraSaleChangeExt> selectByExample(TraSaleChangeExtExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TRA_SALE_CHANGE_EXT
     *
     * @mbggenerated Fri Feb 24 15:34:26 CST 2017
     */
    TraSaleChangeExt selectByPrimaryKey(Long saleChangeNo);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TRA_SALE_CHANGE_EXT
     *
     * @mbggenerated Fri Feb 24 15:34:26 CST 2017
     */
    int updateByExampleSelective(@Param("record") TraSaleChangeExt record, @Param("example") TraSaleChangeExtExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TRA_SALE_CHANGE_EXT
     *
     * @mbggenerated Fri Feb 24 15:34:26 CST 2017
     */
    int updateByExample(@Param("record") TraSaleChangeExt record, @Param("example") TraSaleChangeExtExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TRA_SALE_CHANGE_EXT
     *
     * @mbggenerated Fri Feb 24 15:34:26 CST 2017
     */
    int updateByPrimaryKeySelective(TraSaleChangeExt record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TRA_SALE_CHANGE_EXT
     *
     * @mbggenerated Fri Feb 24 15:34:26 CST 2017
     */
    int updateByPrimaryKey(TraSaleChangeExt record);
    
    List<TraSaleChangeExt> queryObjByKey(Page<TraSaleChangeExt> page, TraSaleChangeExtVo entity);
    
    List<TraSaleChangeExt> queryObjByEntity(TraSaleChangeExtVo entity);
    
    TraSaleChangeExt queryByBuyChangeNo(Long buyChangeNo);
}