package com.tempus.gss.product.tra.dao;

import com.tempus.gss.product.tra.api.entity.TraSupplier;
import com.tempus.gss.product.tra.api.entity.TraSupplierExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface TraSupplierDao {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TRA_SUPPLIER
     *
     * @mbggenerated Fri Feb 24 15:34:26 CST 2017
     */
    int countByExample(TraSupplierExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TRA_SUPPLIER
     *
     * @mbggenerated Fri Feb 24 15:34:26 CST 2017
     */
    int deleteByExample(TraSupplierExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TRA_SUPPLIER
     *
     * @mbggenerated Fri Feb 24 15:34:26 CST 2017
     */
    int deleteByPrimaryKey(Long supplierNo);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TRA_SUPPLIER
     *
     * @mbggenerated Fri Feb 24 15:34:26 CST 2017
     */
    int insert(TraSupplier record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TRA_SUPPLIER
     *
     * @mbggenerated Fri Feb 24 15:34:26 CST 2017
     */
    int insertSelective(TraSupplier record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TRA_SUPPLIER
     *
     * @mbggenerated Fri Feb 24 15:34:26 CST 2017
     */
    List<TraSupplier> selectByExample(TraSupplierExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TRA_SUPPLIER
     *
     * @mbggenerated Fri Feb 24 15:34:26 CST 2017
     */
    TraSupplier selectByPrimaryKey(Long supplierNo);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TRA_SUPPLIER
     *
     * @mbggenerated Fri Feb 24 15:34:26 CST 2017
     */
    int updateByExampleSelective(@Param("record") TraSupplier record, @Param("example") TraSupplierExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TRA_SUPPLIER
     *
     * @mbggenerated Fri Feb 24 15:34:26 CST 2017
     */
    int updateByExample(@Param("record") TraSupplier record, @Param("example") TraSupplierExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TRA_SUPPLIER
     *
     * @mbggenerated Fri Feb 24 15:34:26 CST 2017
     */
    int updateByPrimaryKeySelective(TraSupplier record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TRA_SUPPLIER
     *
     * @mbggenerated Fri Feb 24 15:34:26 CST 2017
     */
    int updateByPrimaryKey(TraSupplier record);
}