
package com.tempus.gss.product.ift.api.entity.webservice.settt;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

import com.tempus.gss.product.ift.api.entity.webservice.InpayVo;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "InsaleService", targetNamespace = "http://tempusservice.tempus.com")
@XmlSeeAlso({
    ObjectSettFactory.class
})
public interface InsaleService {


    /**
     * 
     * @param inpayvo
     * @return
     *     returns com.tempus.gss.product.ift.api.entity.webservice.settt.ReturnInfo
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "addInsalepayment", targetNamespace = "http://tempusservice.tempus.com", className = "com.tempus.gss.product.ift.api.entity.webservice.settt.AddInsalepayment")
    @ResponseWrapper(localName = "addInsalepaymentResponse", targetNamespace = "http://tempusservice.tempus.com", className = "com.tempus.gss.product.ift.api.entity.webservice.settt.AddInsalepaymentResponse")
    public ReturnSettInfo addInsalepayment(
        @WebParam(name = "inpayvo", targetNamespace = "")
        InpayVo inpayvo);

    /**
     * 
     * @param inallsalevo
     * @return
     *     returns com.tempus.gss.product.ift.api.entity.webservice.settt.ReturnInfo
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "addInallsale", targetNamespace = "http://tempusservice.tempus.com", className = "com.tempus.gss.product.ift.api.entity.webservice.settt.AddInallsale")
    @ResponseWrapper(localName = "addInallsaleResponse", targetNamespace = "http://tempusservice.tempus.com", className = "com.tempus.gss.product.ift.api.entity.webservice.settt.AddInallsaleResponse")
    public ReturnSettInfo addInallsale(
        @WebParam(name = "inallsalevo", targetNamespace = "")
        InallsaleVo inallsalevo);

    /**
     * 
     * @param inothersvo
     * @return
     *     returns com.tempus.gss.product.ift.api.entity.webservice.settt.ReturnInfo
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "addInOthers", targetNamespace = "http://tempusservice.tempus.com", className = "com.tempus.gss.product.ift.api.entity.webservice.settt.AddInOthers")
    @ResponseWrapper(localName = "addInOthersResponse", targetNamespace = "http://tempusservice.tempus.com", className = "com.tempus.gss.product.ift.api.entity.webservice.settt.AddInOthersResponse")
    public ReturnSettInfo addInOthers(
        @WebParam(name = "inothersvo", targetNamespace = "")
        InOthersVo inothersvo);

}
