
package com.tempus.gss.product.ift.api.entity.webservice.settt;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "InsaleService", targetNamespace = "http://tempusservice.tempus.com", wsdlLocation = "http://172.16.3.242:8080/accounts/ws/insaleservice?wsdl")
public class InsaleService_Service
    extends Service
{

    private final static URL INSALESERVICE_WSDL_LOCATION;
    private final static WebServiceException INSALESERVICE_EXCEPTION;
    private final static QName INSALESERVICE_QNAME = new QName("http://tempusservice.tempus.com", "InsaleService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://172.16.3.242:8080/accounts/ws/insaleservice?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        INSALESERVICE_WSDL_LOCATION = url;
        INSALESERVICE_EXCEPTION = e;
    }

    public InsaleService_Service() {
        super(__getWsdlLocation(), INSALESERVICE_QNAME);
    }

    public InsaleService_Service(WebServiceFeature... features) {
        super(__getWsdlLocation(), INSALESERVICE_QNAME, features);
    }

    public InsaleService_Service(URL wsdlLocation) {
        super(wsdlLocation, INSALESERVICE_QNAME);
    }

    public InsaleService_Service(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, INSALESERVICE_QNAME, features);
    }

    public InsaleService_Service(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public InsaleService_Service(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns InsaleService
     */
    @WebEndpoint(name = "InsaleServicePort")
    public InsaleService getInsaleServicePort() {
        return super.getPort(new QName("http://tempusservice.tempus.com", "InsaleServicePort"), InsaleService.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns InsaleService
     */
    @WebEndpoint(name = "InsaleServicePort")
    public InsaleService getInsaleServicePort(WebServiceFeature... features) {
        return super.getPort(new QName("http://tempusservice.tempus.com", "InsaleServicePort"), InsaleService.class, features);
    }

    private static URL __getWsdlLocation() {
        if (INSALESERVICE_EXCEPTION!= null) {
            throw INSALESERVICE_EXCEPTION;
        }
        return INSALESERVICE_WSDL_LOCATION;
    }

}
