
package com.tempus.gss.product.ift.api.entity.webservice;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "InsaleErrorService", targetNamespace = "http://tempusservice.tempus.com")
@XmlSeeAlso({
    ObjectFactoryapi.class
})
public interface InsaleErrorService {


    /**
     * 
     * @param inrefundapprefvo
     * @return
     *     returns com.tempus.gss.product.ift.api.entity.webservice.ReturnInfo1
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "addInRefundAppref", targetNamespace = "http://tempusservice.tempus.com", className = "com.tempus.gss.product.ift.api.entity.webservice.AddInRefundAppref")
    @ResponseWrapper(localName = "addInRefundApprefResponse", targetNamespace = "http://tempusservice.tempus.com", className = "com.tempus.gss.product.ift.api.entity.webservice.AddInRefundApprefResponse")
    public ReturnInfo1 addInRefundAppref(
        @WebParam(name = "inrefundapprefvo", targetNamespace = "")
        InRefundApprefVo inrefundapprefvo);

    /**
     * 
     * @param inerrordetailvo
     * @return
     *     returns com.tempus.gss.product.ift.api.entity.webservice.ReturnInfo1
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "addInsaleInerrorment", targetNamespace = "http://tempusservice.tempus.com", className = "com.tempus.gss.product.ift.api.entity.webservice.AddInsaleInerrorment")
    @ResponseWrapper(localName = "addInsaleInerrormentResponse", targetNamespace = "http://tempusservice.tempus.com", className = "com.tempus.gss.product.ift.api.entity.webservice.AddInsaleInerrormentResponse")
    public ReturnInfo1 addInsaleInerrorment(
        @WebParam(name = "inerrordetailvo", targetNamespace = "")
        InerrordetailVo inerrordetailvo);

    /**
     * 
     * @param settlementId
     * @return
     *     returns com.tempus.gss.product.ift.api.entity.webservice.ReturnInfo1
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "deleteInRefundAppref", targetNamespace = "http://tempusservice.tempus.com", className = "com.tempus.gss.product.ift.api.entity.webservice.DeleteInRefundAppref")
    @ResponseWrapper(localName = "deleteInRefundApprefResponse", targetNamespace = "http://tempusservice.tempus.com", className = "com.tempus.gss.product.ift.api.entity.webservice.DeleteInRefundApprefResponse")
    public ReturnInfo1 deleteInRefundAppref(
        @WebParam(name = "settlementId", targetNamespace = "")
        Long settlementId);

}
