package com.tempus.gss.product.tra.api.entity;

import java.io.Serializable;
import java.util.Date;

public class TraPassenger  implements Serializable {
    /**
	 * 
	 */
	private static final long serialVersionUID = 1L;

	/**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TRA_PASSENGER.PASSENGER_NO
     *
     * @mbggenerated Fri Feb 24 15:34:26 CST 2017
     */
    private Long passengerNo;//乘客编号

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TRA_PASSENGER.OWNER
     *
     * @mbggenerated Fri Feb 24 15:34:26 CST 2017
     */
    private Integer owner;//数据归属单位

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TRA_PASSENGER.ID
     *
     * @mbggenerated Fri Feb 24 15:34:26 CST 2017
     */
    private Long id;


    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TRA_PASSENGER.PASSENGER_TYPE
     *
     * @mbggenerated Fri Feb 24 15:34:26 CST 2017
     */
    private String passengerType;//乘客类型  ADT 成人 CHD 儿童  INF婴儿

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TRA_PASSENGER.NAME
     *
     * @mbggenerated Fri Feb 24 15:34:26 CST 2017
     */
    private String name;//名

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TRA_PASSENGER.CERT_TYPE
     *
     * @mbggenerated Fri Feb 24 15:34:26 CST 2017
     */
    private String certType;//证件类型 PP护照 NI身份证 ID其它证件

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TRA_PASSENGER.CERT_NO
     *
     * @mbggenerated Fri Feb 24 15:34:26 CST 2017
     */
    private String certNo;//证件编号

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TRA_PASSENGER.CERT_VALID
     *
     * @mbggenerated Fri Feb 24 15:34:26 CST 2017
     */
    private Date certValid;//证件有效期

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TRA_PASSENGER.PASSENGER_BIRTH
     *
     * @mbggenerated Fri Feb 24 15:34:26 CST 2017
     */
    private Date passengerBirth;//乘客出生日期

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TRA_PASSENGER.NATIONALITY
     *
     * @mbggenerated Fri Feb 24 15:34:26 CST 2017
     */
    private String nationality;//国籍

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TRA_PASSENGER.GENDER
     *
     * @mbggenerated Fri Feb 24 15:34:26 CST 2017
     */
    private String gender;//性别 1:男  0女

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TRA_PASSENGER.MODIFIER
     *
     * @mbggenerated Fri Feb 24 15:34:26 CST 2017
     */
    private String modifier;//操作人

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TRA_PASSENGER.VALID
     *
     * @mbggenerated Fri Feb 24 15:34:26 CST 2017
     */
    private Byte valid;//启用状态

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TRA_PASSENGER.CREATE_TIME
     *
     * @mbggenerated Fri Feb 24 15:34:26 CST 2017
     */
    private Date createTime;//创建时间

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TRA_PASSENGER.CREATOR
     *
     * @mbggenerated Fri Feb 24 15:34:26 CST 2017
     */
    private String creator;//创建人

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TRA_PASSENGER.PASSENGER_NO
     *
     * @return the value of TRA_PASSENGER.PASSENGER_NO
     *
     * @mbggenerated Fri Feb 24 15:34:26 CST 2017
     */
    public Long getPassengerNo() {
        return passengerNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TRA_PASSENGER.PASSENGER_NO
     *
     * @param passengerNo the value for TRA_PASSENGER.PASSENGER_NO
     *
     * @mbggenerated Fri Feb 24 15:34:26 CST 2017
     */
    public void setPassengerNo(Long passengerNo) {
        this.passengerNo = passengerNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TRA_PASSENGER.OWNER
     *
     * @return the value of TRA_PASSENGER.OWNER
     *
     * @mbggenerated Fri Feb 24 15:34:26 CST 2017
     */
    public Integer getOwner() {
        return owner;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TRA_PASSENGER.OWNER
     *
     * @param owner the value for TRA_PASSENGER.OWNER
     *
     * @mbggenerated Fri Feb 24 15:34:26 CST 2017
     */
    public void setOwner(Integer owner) {
        this.owner = owner;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TRA_PASSENGER.ID
     *
     * @return the value of TRA_PASSENGER.ID
     *
     * @mbggenerated Fri Feb 24 15:34:26 CST 2017
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TRA_PASSENGER.ID
     *
     * @param id the value for TRA_PASSENGER.ID
     *
     * @mbggenerated Fri Feb 24 15:34:26 CST 2017
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TRA_PASSENGER.PASSENGER_TYPE
     *
     * @return the value of TRA_PASSENGER.PASSENGER_TYPE
     *
     * @mbggenerated Fri Feb 24 15:34:26 CST 2017
     */
    public String getPassengerType() {
        return passengerType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TRA_PASSENGER.PASSENGER_TYPE
     *
     * @param passengerType the value for TRA_PASSENGER.PASSENGER_TYPE
     *
     * @mbggenerated Fri Feb 24 15:34:26 CST 2017
     */
    public void setPassengerType(String passengerType) {
        this.passengerType = passengerType == null ? null : passengerType.trim();
    }


    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TRA_PASSENGER.NAME
     *
     * @return the value of TRA_PASSENGER.NAME
     *
     * @mbggenerated Fri Feb 24 15:34:26 CST 2017
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TRA_PASSENGER.NAME
     *
     * @param name the value for TRA_PASSENGER.NAME
     *
     * @mbggenerated Fri Feb 24 15:34:26 CST 2017
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TRA_PASSENGER.CERT_TYPE
     *
     * @return the value of TRA_PASSENGER.CERT_TYPE
     *
     * @mbggenerated Fri Feb 24 15:34:26 CST 2017
     */
    public String getCertType() {
        return certType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TRA_PASSENGER.CERT_TYPE
     *
     * @param certType the value for TRA_PASSENGER.CERT_TYPE
     *
     * @mbggenerated Fri Feb 24 15:34:26 CST 2017
     */
    public void setCertType(String certType) {
        this.certType = certType == null ? null : certType.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TRA_PASSENGER.CERT_NO
     *
     * @return the value of TRA_PASSENGER.CERT_NO
     *
     * @mbggenerated Fri Feb 24 15:34:26 CST 2017
     */
    public String getCertNo() {
        return certNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TRA_PASSENGER.CERT_NO
     *
     * @param certNo the value for TRA_PASSENGER.CERT_NO
     *
     * @mbggenerated Fri Feb 24 15:34:26 CST 2017
     */
    public void setCertNo(String certNo) {
        this.certNo = certNo == null ? null : certNo.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TRA_PASSENGER.CERT_VALID
     *
     * @return the value of TRA_PASSENGER.CERT_VALID
     *
     * @mbggenerated Fri Feb 24 15:34:26 CST 2017
     */
    public Date getCertValid() {
        return certValid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TRA_PASSENGER.CERT_VALID
     *
     * @param certValid the value for TRA_PASSENGER.CERT_VALID
     *
     * @mbggenerated Fri Feb 24 15:34:26 CST 2017
     */
    public void setCertValid(Date certValid) {
        this.certValid = certValid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TRA_PASSENGER.PASSENGER_BIRTH
     *
     * @return the value of TRA_PASSENGER.PASSENGER_BIRTH
     *
     * @mbggenerated Fri Feb 24 15:34:26 CST 2017
     */
    public Date getPassengerBirth() {
        return passengerBirth;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TRA_PASSENGER.PASSENGER_BIRTH
     *
     * @param passengerBirth the value for TRA_PASSENGER.PASSENGER_BIRTH
     *
     * @mbggenerated Fri Feb 24 15:34:26 CST 2017
     */
    public void setPassengerBirth(Date passengerBirth) {
        this.passengerBirth = passengerBirth;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TRA_PASSENGER.NATIONALITY
     *
     * @return the value of TRA_PASSENGER.NATIONALITY
     *
     * @mbggenerated Fri Feb 24 15:34:26 CST 2017
     */
    public String getNationality() {
        return nationality;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TRA_PASSENGER.NATIONALITY
     *
     * @param nationality the value for TRA_PASSENGER.NATIONALITY
     *
     * @mbggenerated Fri Feb 24 15:34:26 CST 2017
     */
    public void setNationality(String nationality) {
        this.nationality = nationality == null ? null : nationality.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TRA_PASSENGER.GENDER
     *
     * @return the value of TRA_PASSENGER.GENDER
     *
     * @mbggenerated Fri Feb 24 15:34:26 CST 2017
     */
    public String getGender() {
        return gender;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TRA_PASSENGER.GENDER
     *
     * @param gender the value for TRA_PASSENGER.GENDER
     *
     * @mbggenerated Fri Feb 24 15:34:26 CST 2017
     */
    public void setGender(String gender) {
        this.gender = gender == null ? null : gender.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TRA_PASSENGER.MODIFIER
     *
     * @return the value of TRA_PASSENGER.MODIFIER
     *
     * @mbggenerated Fri Feb 24 15:34:26 CST 2017
     */
    public String getModifier() {
        return modifier;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TRA_PASSENGER.MODIFIER
     *
     * @param modifier the value for TRA_PASSENGER.MODIFIER
     *
     * @mbggenerated Fri Feb 24 15:34:26 CST 2017
     */
    public void setModifier(String modifier) {
        this.modifier = modifier == null ? null : modifier.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TRA_PASSENGER.VALID
     *
     * @return the value of TRA_PASSENGER.VALID
     *
     * @mbggenerated Fri Feb 24 15:34:26 CST 2017
     */
    public Byte getValid() {
        return valid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TRA_PASSENGER.VALID
     *
     * @param valid the value for TRA_PASSENGER.VALID
     *
     * @mbggenerated Fri Feb 24 15:34:26 CST 2017
     */
    public void setValid(Byte valid) {
        this.valid = valid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TRA_PASSENGER.CREATE_TIME
     *
     * @return the value of TRA_PASSENGER.CREATE_TIME
     *
     * @mbggenerated Fri Feb 24 15:34:26 CST 2017
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TRA_PASSENGER.CREATE_TIME
     *
     * @param createTime the value for TRA_PASSENGER.CREATE_TIME
     *
     * @mbggenerated Fri Feb 24 15:34:26 CST 2017
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TRA_PASSENGER.CREATOR
     *
     * @return the value of TRA_PASSENGER.CREATOR
     *
     * @mbggenerated Fri Feb 24 15:34:26 CST 2017
     */
    public String getCreator() {
        return creator;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TRA_PASSENGER.CREATOR
     *
     * @param creator the value for TRA_PASSENGER.CREATOR
     *
     * @mbggenerated Fri Feb 24 15:34:26 CST 2017
     */
    public void setCreator(String creator) {
        this.creator = creator == null ? null : creator.trim();
    }
}