package com.tempus.gss.product.tra.api.entity;

import java.io.Serializable;
import java.math.BigDecimal;
import java.util.Date;

public class TraProfitControl  implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TRA_PROFIT_CONTROL.PROFIT_CONTROL_NO
     *
     * @mbggenerated Fri Feb 24 15:34:26 CST 2017
     */
    private Long profitControlNo;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TRA_PROFIT_CONTROL.ID
     *
     * @mbggenerated Fri Feb 24 15:34:26 CST 2017
     */
    private Long id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TRA_PROFIT_CONTROL.OWNER
     *
     * @mbggenerated Fri Feb 24 15:34:26 CST 2017
     */
    private Integer owner;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TRA_PROFIT_CONTROL.INSURANCE_NO
     *
     * @mbggenerated Fri Feb 24 15:34:26 CST 2017
     */
    private String insuranceNo;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TRA_PROFIT_CONTROL.CUSTOMER_TYPE_NO
     *
     * @mbggenerated Fri Feb 24 15:34:26 CST 2017
     */
    private Long customerTypeNo;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TRA_PROFIT_CONTROL.brokerage
     *
     * @mbggenerated Fri Feb 24 15:34:26 CST 2017
     */
    private BigDecimal brokerage;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TRA_PROFIT_CONTROL.CREATE_TIME
     *
     * @mbggenerated Fri Feb 24 15:34:26 CST 2017
     */
    private Date createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TRA_PROFIT_CONTROL.MODIFY_TIME
     *
     * @mbggenerated Fri Feb 24 15:34:26 CST 2017
     */
    private Date modifyTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TRA_PROFIT_CONTROL.CREATOR
     *
     * @mbggenerated Fri Feb 24 15:34:26 CST 2017
     */
    private String creator;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TRA_PROFIT_CONTROL.MODIFIER
     *
     * @mbggenerated Fri Feb 24 15:34:26 CST 2017
     */
    private String modifier;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TRA_PROFIT_CONTROL.VALID
     *
     * @mbggenerated Fri Feb 24 15:34:26 CST 2017
     */
    private Boolean valid;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TRA_PROFIT_CONTROL.PROFIT_CONTROL_NO
     *
     * @return the value of TRA_PROFIT_CONTROL.PROFIT_CONTROL_NO
     *
     * @mbggenerated Fri Feb 24 15:34:26 CST 2017
     */
    public Long getProfitControlNo() {
        return profitControlNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TRA_PROFIT_CONTROL.PROFIT_CONTROL_NO
     *
     * @param profitControlNo the value for TRA_PROFIT_CONTROL.PROFIT_CONTROL_NO
     *
     * @mbggenerated Fri Feb 24 15:34:26 CST 2017
     */
    public void setProfitControlNo(Long profitControlNo) {
        this.profitControlNo = profitControlNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TRA_PROFIT_CONTROL.ID
     *
     * @return the value of TRA_PROFIT_CONTROL.ID
     *
     * @mbggenerated Fri Feb 24 15:34:26 CST 2017
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TRA_PROFIT_CONTROL.ID
     *
     * @param id the value for TRA_PROFIT_CONTROL.ID
     *
     * @mbggenerated Fri Feb 24 15:34:26 CST 2017
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TRA_PROFIT_CONTROL.OWNER
     *
     * @return the value of TRA_PROFIT_CONTROL.OWNER
     *
     * @mbggenerated Fri Feb 24 15:34:26 CST 2017
     */
    public Integer getOwner() {
        return owner;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TRA_PROFIT_CONTROL.OWNER
     *
     * @param owner the value for TRA_PROFIT_CONTROL.OWNER
     *
     * @mbggenerated Fri Feb 24 15:34:26 CST 2017
     */
    public void setOwner(Integer owner) {
        this.owner = owner;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TRA_PROFIT_CONTROL.INSURANCE_NO
     *
     * @return the value of TRA_PROFIT_CONTROL.INSURANCE_NO
     *
     * @mbggenerated Fri Feb 24 15:34:26 CST 2017
     */
    public String getInsuranceNo() {
        return insuranceNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TRA_PROFIT_CONTROL.INSURANCE_NO
     *
     * @param insuranceNo the value for TRA_PROFIT_CONTROL.INSURANCE_NO
     *
     * @mbggenerated Fri Feb 24 15:34:26 CST 2017
     */
    public void setInsuranceNo(String insuranceNo) {
        this.insuranceNo = insuranceNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TRA_PROFIT_CONTROL.CUSTOMER_TYPE_NO
     *
     * @return the value of TRA_PROFIT_CONTROL.CUSTOMER_TYPE_NO
     *
     * @mbggenerated Fri Feb 24 15:34:26 CST 2017
     */
    public Long getCustomerTypeNo() {
        return customerTypeNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TRA_PROFIT_CONTROL.CUSTOMER_TYPE_NO
     *
     * @param customerTypeNo the value for TRA_PROFIT_CONTROL.CUSTOMER_TYPE_NO
     *
     * @mbggenerated Fri Feb 24 15:34:26 CST 2017
     */
    public void setCustomerTypeNo(Long customerTypeNo) {
        this.customerTypeNo = customerTypeNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TRA_PROFIT_CONTROL.brokerage
     *
     * @return the value of TRA_PROFIT_CONTROL.brokerage
     *
     * @mbggenerated Fri Feb 24 15:34:26 CST 2017
     */
    public BigDecimal getBrokerage() {
        return brokerage;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TRA_PROFIT_CONTROL.brokerage
     *
     * @param brokerage the value for TRA_PROFIT_CONTROL.brokerage
     *
     * @mbggenerated Fri Feb 24 15:34:26 CST 2017
     */
    public void setBrokerage(BigDecimal brokerage) {
        this.brokerage = brokerage;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TRA_PROFIT_CONTROL.CREATE_TIME
     *
     * @return the value of TRA_PROFIT_CONTROL.CREATE_TIME
     *
     * @mbggenerated Fri Feb 24 15:34:26 CST 2017
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TRA_PROFIT_CONTROL.CREATE_TIME
     *
     * @param createTime the value for TRA_PROFIT_CONTROL.CREATE_TIME
     *
     * @mbggenerated Fri Feb 24 15:34:26 CST 2017
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TRA_PROFIT_CONTROL.MODIFY_TIME
     *
     * @return the value of TRA_PROFIT_CONTROL.MODIFY_TIME
     *
     * @mbggenerated Fri Feb 24 15:34:26 CST 2017
     */
    public Date getModifyTime() {
        return modifyTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TRA_PROFIT_CONTROL.MODIFY_TIME
     *
     * @param modifyTime the value for TRA_PROFIT_CONTROL.MODIFY_TIME
     *
     * @mbggenerated Fri Feb 24 15:34:26 CST 2017
     */
    public void setModifyTime(Date modifyTime) {
        this.modifyTime = modifyTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TRA_PROFIT_CONTROL.CREATOR
     *
     * @return the value of TRA_PROFIT_CONTROL.CREATOR
     *
     * @mbggenerated Fri Feb 24 15:34:26 CST 2017
     */
    public String getCreator() {
        return creator;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TRA_PROFIT_CONTROL.CREATOR
     *
     * @param creator the value for TRA_PROFIT_CONTROL.CREATOR
     *
     * @mbggenerated Fri Feb 24 15:34:26 CST 2017
     */
    public void setCreator(String creator) {
        this.creator = creator == null ? null : creator.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TRA_PROFIT_CONTROL.MODIFIER
     *
     * @return the value of TRA_PROFIT_CONTROL.MODIFIER
     *
     * @mbggenerated Fri Feb 24 15:34:26 CST 2017
     */
    public String getModifier() {
        return modifier;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TRA_PROFIT_CONTROL.MODIFIER
     *
     * @param modifier the value for TRA_PROFIT_CONTROL.MODIFIER
     *
     * @mbggenerated Fri Feb 24 15:34:26 CST 2017
     */
    public void setModifier(String modifier) {
        this.modifier = modifier == null ? null : modifier.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TRA_PROFIT_CONTROL.VALID
     *
     * @return the value of TRA_PROFIT_CONTROL.VALID
     *
     * @mbggenerated Fri Feb 24 15:34:26 CST 2017
     */
    public Boolean getValid() {
        return valid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TRA_PROFIT_CONTROL.VALID
     *
     * @param valid the value for TRA_PROFIT_CONTROL.VALID
     *
     * @mbggenerated Fri Feb 24 15:34:26 CST 2017
     */
    public void setValid(Boolean valid) {
        this.valid = valid;
    }
}