package com.tempus.gss.product.tra.api.entity;

import com.fasterxml.jackson.databind.annotation.JsonSerialize;
import com.tempus.gss.serializer.LongSerializer;

import java.io.Serializable;
import java.util.Date;

public class TraSaleChangeDetail  implements Serializable {
    /**
	 * 
	 */
	private static final long serialVersionUID = 1L;

	/**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TRA_SALE_CHANGE_DETAIL.SALE_CHANGE_DETAIL_NO
     *
     * @mbggenerated Fri Feb 24 15:34:26 CST 2017
     */
    @JsonSerialize(using = LongSerializer.class)
    private Long saleChangeDetailNo;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TRA_SALE_CHANGE_DETAIL.ID
     *
     * @mbggenerated Fri Feb 24 15:34:26 CST 2017
     */
    @JsonSerialize(using = LongSerializer.class)
    private Long id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TRA_SALE_CHANGE_DETAIL.OWNER
     *
     * @mbggenerated Fri Feb 24 15:34:26 CST 2017
     */
    private Integer owner;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TRA_SALE_CHANGE_DETAIL.SALE_CHANGE_NO
     *
     * @mbggenerated Fri Feb 24 15:34:26 CST 2017
     */
    @JsonSerialize(using = LongSerializer.class)
    private Long saleChangeNo;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TRA_SALE_CHANGE_DETAIL.BUY_CHANGE_NO
     *
     * @mbggenerated Fri Feb 24 15:34:26 CST 2017
     */
    @JsonSerialize(using = LongSerializer.class)
    private Long buyChangeNo;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TRA_SALE_CHANGE_DETAIL.SALE_ORDER_DETAIL_NO
     *
     * @mbggenerated Fri Feb 24 15:34:26 CST 2017
     */
    @JsonSerialize(using = LongSerializer.class)
    private Long saleOrderDetailNo;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TRA_SALE_CHANGE_DETAIL.CREATOR
     *
     * @mbggenerated Fri Feb 24 15:34:26 CST 2017
     */
    private String creator;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TRA_SALE_CHANGE_DETAIL.CREATE_TIME
     *
     * @mbggenerated Fri Feb 24 15:34:26 CST 2017
     */
    private Date createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TRA_SALE_CHANGE_DETAIL.VALID
     *
     * @mbggenerated Fri Feb 24 15:34:26 CST 2017
     */
    private Byte valid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TRA_SALE_CHANGE_DETAIL.SALE_ORDER_NO
     *
     * @mbggenerated Fri Feb 24 15:34:26 CST 2017
     */
    @JsonSerialize(using = LongSerializer.class)
    private Long saleOrderNo;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TRA_SALE_CHANGE_DETAIL.STATUS
     *
     * @mbggenerated Fri Feb 24 15:34:26 CST 2017
     */
    private String status;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TRA_SALE_CHANGE_DETAIL.MODIFIER
     *
     * @mbggenerated Fri Feb 24 15:34:26 CST 2017
     */
    private String modifier;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TRA_SALE_CHANGE_DETAIL.MODIFY_TIME
     *
     * @mbggenerated Fri Feb 24 15:34:26 CST 2017
     */
    private Date modifyTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TRA_SALE_CHANGE_DETAIL.SALE_CHANGE_DETAIL_NO
     *
     * @return the value of TRA_SALE_CHANGE_DETAIL.SALE_CHANGE_DETAIL_NO
     *
     * @mbggenerated Fri Feb 24 15:34:26 CST 2017
     */
    public Long getSaleChangeDetailNo() {
        return saleChangeDetailNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TRA_SALE_CHANGE_DETAIL.SALE_CHANGE_DETAIL_NO
     *
     * @param saleChangeDetailNo the value for TRA_SALE_CHANGE_DETAIL.SALE_CHANGE_DETAIL_NO
     *
     * @mbggenerated Fri Feb 24 15:34:26 CST 2017
     */
    public void setSaleChangeDetailNo(Long saleChangeDetailNo) {
        this.saleChangeDetailNo = saleChangeDetailNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TRA_SALE_CHANGE_DETAIL.ID
     *
     * @return the value of TRA_SALE_CHANGE_DETAIL.ID
     *
     * @mbggenerated Fri Feb 24 15:34:26 CST 2017
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TRA_SALE_CHANGE_DETAIL.ID
     *
     * @param id the value for TRA_SALE_CHANGE_DETAIL.ID
     *
     * @mbggenerated Fri Feb 24 15:34:26 CST 2017
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TRA_SALE_CHANGE_DETAIL.OWNER
     *
     * @return the value of TRA_SALE_CHANGE_DETAIL.OWNER
     *
     * @mbggenerated Fri Feb 24 15:34:26 CST 2017
     */
    public Integer getOwner() {
        return owner;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TRA_SALE_CHANGE_DETAIL.OWNER
     *
     * @param owner the value for TRA_SALE_CHANGE_DETAIL.OWNER
     *
     * @mbggenerated Fri Feb 24 15:34:26 CST 2017
     */
    public void setOwner(Integer owner) {
        this.owner = owner;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TRA_SALE_CHANGE_DETAIL.SALE_CHANGE_NO
     *
     * @return the value of TRA_SALE_CHANGE_DETAIL.SALE_CHANGE_NO
     *
     * @mbggenerated Fri Feb 24 15:34:26 CST 2017
     */
    public Long getSaleChangeNo() {
        return saleChangeNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TRA_SALE_CHANGE_DETAIL.SALE_CHANGE_NO
     *
     * @param saleChangeNo the value for TRA_SALE_CHANGE_DETAIL.SALE_CHANGE_NO
     *
     * @mbggenerated Fri Feb 24 15:34:26 CST 2017
     */
    public void setSaleChangeNo(Long saleChangeNo) {
        this.saleChangeNo = saleChangeNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TRA_SALE_CHANGE_DETAIL.BUY_CHANGE_NO
     *
     * @return the value of TRA_SALE_CHANGE_DETAIL.BUY_CHANGE_NO
     *
     * @mbggenerated Fri Feb 24 15:34:26 CST 2017
     */
    public Long getBuyChangeNo() {
        return buyChangeNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TRA_SALE_CHANGE_DETAIL.BUY_CHANGE_NO
     *
     * @param buyChangeNo the value for TRA_SALE_CHANGE_DETAIL.BUY_CHANGE_NO
     *
     * @mbggenerated Fri Feb 24 15:34:26 CST 2017
     */
    public void setBuyChangeNo(Long buyChangeNo) {
        this.buyChangeNo = buyChangeNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TRA_SALE_CHANGE_DETAIL.SALE_ORDER_DETAIL_NO
     *
     * @return the value of TRA_SALE_CHANGE_DETAIL.SALE_ORDER_DETAIL_NO
     *
     * @mbggenerated Fri Feb 24 15:34:26 CST 2017
     */
    public Long getSaleOrderDetailNo() {
        return saleOrderDetailNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TRA_SALE_CHANGE_DETAIL.SALE_ORDER_DETAIL_NO
     *
     * @param saleOrderDetailNo the value for TRA_SALE_CHANGE_DETAIL.SALE_ORDER_DETAIL_NO
     *
     * @mbggenerated Fri Feb 24 15:34:26 CST 2017
     */
    public void setSaleOrderDetailNo(Long saleOrderDetailNo) {
        this.saleOrderDetailNo = saleOrderDetailNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TRA_SALE_CHANGE_DETAIL.CREATOR
     *
     * @return the value of TRA_SALE_CHANGE_DETAIL.CREATOR
     *
     * @mbggenerated Fri Feb 24 15:34:26 CST 2017
     */
    public String getCreator() {
        return creator;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TRA_SALE_CHANGE_DETAIL.CREATOR
     *
     * @param creator the value for TRA_SALE_CHANGE_DETAIL.CREATOR
     *
     * @mbggenerated Fri Feb 24 15:34:26 CST 2017
     */
    public void setCreator(String creator) {
        this.creator = creator == null ? null : creator.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TRA_SALE_CHANGE_DETAIL.CREATE_TIME
     *
     * @return the value of TRA_SALE_CHANGE_DETAIL.CREATE_TIME
     *
     * @mbggenerated Fri Feb 24 15:34:26 CST 2017
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TRA_SALE_CHANGE_DETAIL.CREATE_TIME
     *
     * @param createTime the value for TRA_SALE_CHANGE_DETAIL.CREATE_TIME
     *
     * @mbggenerated Fri Feb 24 15:34:26 CST 2017
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TRA_SALE_CHANGE_DETAIL.VALID
     *
     * @return the value of TRA_SALE_CHANGE_DETAIL.VALID
     *
     * @mbggenerated Fri Feb 24 15:34:26 CST 2017
     */
    public Byte getValid() {
        return valid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TRA_SALE_CHANGE_DETAIL.VALID
     *
     * @param valid the value for TRA_SALE_CHANGE_DETAIL.VALID
     *
     * @mbggenerated Fri Feb 24 15:34:26 CST 2017
     */
    public void setValid(Byte valid) {
        this.valid = valid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TRA_SALE_CHANGE_DETAIL.SALE_ORDER_NO
     *
     * @return the value of TRA_SALE_CHANGE_DETAIL.SALE_ORDER_NO
     *
     * @mbggenerated Fri Feb 24 15:34:26 CST 2017
     */
    public Long getSaleOrderNo() {
        return saleOrderNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TRA_SALE_CHANGE_DETAIL.SALE_ORDER_NO
     *
     * @param saleOrderNo the value for TRA_SALE_CHANGE_DETAIL.SALE_ORDER_NO
     *
     * @mbggenerated Fri Feb 24 15:34:26 CST 2017
     */
    public void setSaleOrderNo(Long saleOrderNo) {
        this.saleOrderNo = saleOrderNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TRA_SALE_CHANGE_DETAIL.STATUS
     *
     * @return the value of TRA_SALE_CHANGE_DETAIL.STATUS
     *
     * @mbggenerated Fri Feb 24 15:34:26 CST 2017
     */
    public String getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TRA_SALE_CHANGE_DETAIL.STATUS
     *
     * @param status the value for TRA_SALE_CHANGE_DETAIL.STATUS
     *
     * @mbggenerated Fri Feb 24 15:34:26 CST 2017
     */
    public void setStatus(String status) {
        this.status = status == null ? null : status.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TRA_SALE_CHANGE_DETAIL.MODIFIER
     *
     * @return the value of TRA_SALE_CHANGE_DETAIL.MODIFIER
     *
     * @mbggenerated Fri Feb 24 15:34:26 CST 2017
     */
    public String getModifier() {
        return modifier;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TRA_SALE_CHANGE_DETAIL.MODIFIER
     *
     * @param modifier the value for TRA_SALE_CHANGE_DETAIL.MODIFIER
     *
     * @mbggenerated Fri Feb 24 15:34:26 CST 2017
     */
    public void setModifier(String modifier) {
        this.modifier = modifier == null ? null : modifier.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TRA_SALE_CHANGE_DETAIL.MODIFY_TIME
     *
     * @return the value of TRA_SALE_CHANGE_DETAIL.MODIFY_TIME
     *
     * @mbggenerated Fri Feb 24 15:34:26 CST 2017
     */
    public Date getModifyTime() {
        return modifyTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TRA_SALE_CHANGE_DETAIL.MODIFY_TIME
     *
     * @param modifyTime the value for TRA_SALE_CHANGE_DETAIL.MODIFY_TIME
     *
     * @mbggenerated Fri Feb 24 15:34:26 CST 2017
     */
    public void setModifyTime(Date modifyTime) {
        this.modifyTime = modifyTime;
    }
}