package com.tempus.gss.product.tra.api.entity;

import com.fasterxml.jackson.databind.annotation.JsonSerialize;
import com.tempus.gss.serializer.LongSerializer;

import java.io.Serializable;
import java.math.BigDecimal;
import java.util.Date;

public class TraSaleOrderDetail implements Serializable {
    /**
     *
     */
    private static final long serialVersionUID = 1L;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TRA_SALE_ORDER_DETAIL.SALE_ORDER_DETAIL_NO
     *
     * @mbggenerated Mon Feb 27 15:21:11 CST 2017
     */
    @JsonSerialize(using = LongSerializer.class)
    private Long saleOrderDetailNo;//详情单号

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TRA_SALE_ORDER_DETAIL.id
     *
     * @mbggenerated Mon Feb 27 15:21:11 CST 2017
     */
    private String id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TRA_SALE_ORDER_DETAIL.passenger_no
     *
     * @mbggenerated Mon Feb 27 15:21:11 CST 2017
     */
    @JsonSerialize(using = LongSerializer.class)
    private Long passengerNo;//乘机人编号

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TRA_SALE_ORDER_DETAIL.trainNo
     *
     * @mbggenerated Mon Feb 27 15:21:11 CST 2017
     */
    private String trainno;//车次

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TRA_SALE_ORDER_DETAIL.seatClass
     *
     * @mbggenerated Mon Feb 27 15:21:11 CST 2017
     */
    private String seatclass;//座位类型

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TRA_SALE_ORDER_DETAIL.fromStation
     *
     * @mbggenerated Mon Feb 27 15:21:11 CST 2017
     */
    private String fromstation;//始发站

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TRA_SALE_ORDER_DETAIL.toStation
     *
     * @mbggenerated Mon Feb 27 15:21:11 CST 2017
     */
    private String tostation;//到达站

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TRA_SALE_ORDER_DETAIL.trainDate
     *
     * @mbggenerated Mon Feb 27 15:21:11 CST 2017
     */
    private Date traindate;//出发时间

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TRA_SALE_ORDER_DETAIL.PREMIUM
     *
     * @mbggenerated Mon Feb 27 15:21:11 CST 2017
     */
    private BigDecimal premium;//总金额

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TRA_SALE_ORDER_DETAIL.sale_price
     *
     * @mbggenerated Mon Feb 27 15:21:11 CST 2017
     */
    private BigDecimal salePrice;//销售金额

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TRA_SALE_ORDER_DETAIL.buy_price
     *
     * @mbggenerated Mon Feb 27 15:21:11 CST 2017
     */
    private BigDecimal buyPrice;//采购金额

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TRA_SALE_ORDER_DETAIL.SALE_ORDER_NO
     *
     * @mbggenerated Mon Feb 27 15:21:11 CST 2017
     */
    private Long saleOrderNo;//订单编号

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TRA_SALE_ORDER_DETAIL.CREATE_TIME
     *
     * @mbggenerated Mon Feb 27 15:21:11 CST 2017
     */
    private Date createTime;//创建日期

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TRA_SALE_ORDER_DETAIL.MODIFY_TIME
     *
     * @mbggenerated Mon Feb 27 15:21:11 CST 2017
     */
    private Date modifyTime;//修改日期

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TRA_SALE_ORDER_DETAIL.CREATOR
     *
     * @mbggenerated Mon Feb 27 15:21:11 CST 2017
     */
    private String creator;//创建人

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TRA_SALE_ORDER_DETAIL.MODIFIER
     *
     * @mbggenerated Mon Feb 27 15:21:11 CST 2017
     */
    private String modifier;//修改人

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TRA_SALE_ORDER_DETAIL.VALID
     *
     * @mbggenerated Mon Feb 27 15:21:11 CST 2017
     */
    private Boolean valid;//删除标志

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TRA_SALE_ORDER_DETAIL.OWNER
     *
     * @mbggenerated Mon Feb 27 15:21:11 CST 2017
     */
    private Integer owner;//所有人

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TRA_SALE_ORDER_DETAIL.STATUS
     *
     * @mbggenerated Mon Feb 27 15:21:11 CST 2017
     */
    private Integer status;// 1（已创建），2（支付中），3（出票中），4（已出票）5（退票中），6（改签中） 7（已退），8（已废），9（已改签），10（异常订单）

    private TraPassenger traPassenger;//乘机人

    private String outPassengerNo;//外部乘机人单号
    private String seatNo;//座位号

    private Date departureTime;//出发时间
    private Date arrivalTime;//到达时间
    private BigDecimal brokerage;//手续费
    private BigDecimal serviceFee;//服务费

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TRA_SALE_ORDER_DETAIL.SALE_ORDER_DETAIL_NO
     *
     * @return the value of TRA_SALE_ORDER_DETAIL.SALE_ORDER_DETAIL_NO
     * @mbggenerated Mon Feb 27 15:21:11 CST 2017
     */
    public Long getSaleOrderDetailNo() {
        return saleOrderDetailNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TRA_SALE_ORDER_DETAIL.SALE_ORDER_DETAIL_NO
     *
     * @param saleOrderDetailNo the value for TRA_SALE_ORDER_DETAIL.SALE_ORDER_DETAIL_NO
     * @mbggenerated Mon Feb 27 15:21:11 CST 2017
     */
    public void setSaleOrderDetailNo(Long saleOrderDetailNo) {
        this.saleOrderDetailNo = saleOrderDetailNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TRA_SALE_ORDER_DETAIL.id
     *
     * @return the value of TRA_SALE_ORDER_DETAIL.id
     * @mbggenerated Mon Feb 27 15:21:11 CST 2017
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TRA_SALE_ORDER_DETAIL.id
     *
     * @param id the value for TRA_SALE_ORDER_DETAIL.id
     * @mbggenerated Mon Feb 27 15:21:11 CST 2017
     */
    public void setId(String id) {
        this.id = id == null ? null : id.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TRA_SALE_ORDER_DETAIL.passenger_no
     *
     * @return the value of TRA_SALE_ORDER_DETAIL.passenger_no
     * @mbggenerated Mon Feb 27 15:21:11 CST 2017
     */
    public Long getPassengerNo() {
        return passengerNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TRA_SALE_ORDER_DETAIL.passenger_no
     *
     * @param passengerNo the value for TRA_SALE_ORDER_DETAIL.passenger_no
     * @mbggenerated Mon Feb 27 15:21:11 CST 2017
     */
    public void setPassengerNo(Long passengerNo) {
        this.passengerNo = passengerNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TRA_SALE_ORDER_DETAIL.trainNo
     *
     * @return the value of TRA_SALE_ORDER_DETAIL.trainNo
     * @mbggenerated Mon Feb 27 15:21:11 CST 2017
     */
    public String getTrainno() {
        return trainno;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TRA_SALE_ORDER_DETAIL.trainNo
     *
     * @param trainno the value for TRA_SALE_ORDER_DETAIL.trainNo
     * @mbggenerated Mon Feb 27 15:21:11 CST 2017
     */
    public void setTrainno(String trainno) {
        this.trainno = trainno == null ? null : trainno.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TRA_SALE_ORDER_DETAIL.seatClass
     *
     * @return the value of TRA_SALE_ORDER_DETAIL.seatClass
     * @mbggenerated Mon Feb 27 15:21:11 CST 2017
     */
    public String getSeatclass() {
        return seatclass;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TRA_SALE_ORDER_DETAIL.seatClass
     *
     * @param seatclass the value for TRA_SALE_ORDER_DETAIL.seatClass
     * @mbggenerated Mon Feb 27 15:21:11 CST 2017
     */
    public void setSeatclass(String seatclass) {
        this.seatclass = seatclass;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TRA_SALE_ORDER_DETAIL.fromStation
     *
     * @return the value of TRA_SALE_ORDER_DETAIL.fromStation
     * @mbggenerated Mon Feb 27 15:21:11 CST 2017
     */
    public String getFromstation() {
        return fromstation;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TRA_SALE_ORDER_DETAIL.fromStation
     *
     * @param fromstation the value for TRA_SALE_ORDER_DETAIL.fromStation
     * @mbggenerated Mon Feb 27 15:21:11 CST 2017
     */
    public void setFromstation(String fromstation) {
        this.fromstation = fromstation == null ? null : fromstation.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TRA_SALE_ORDER_DETAIL.toStation
     *
     * @return the value of TRA_SALE_ORDER_DETAIL.toStation
     * @mbggenerated Mon Feb 27 15:21:11 CST 2017
     */
    public String getTostation() {
        return tostation;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TRA_SALE_ORDER_DETAIL.toStation
     *
     * @param tostation the value for TRA_SALE_ORDER_DETAIL.toStation
     * @mbggenerated Mon Feb 27 15:21:11 CST 2017
     */
    public void setTostation(String tostation) {
        this.tostation = tostation == null ? null : tostation.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TRA_SALE_ORDER_DETAIL.trainDate
     *
     * @return the value of TRA_SALE_ORDER_DETAIL.trainDate
     * @mbggenerated Mon Feb 27 15:21:11 CST 2017
     */
    public Date getTraindate() {
        return traindate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TRA_SALE_ORDER_DETAIL.trainDate
     *
     * @param traindate the value for TRA_SALE_ORDER_DETAIL.trainDate
     * @mbggenerated Mon Feb 27 15:21:11 CST 2017
     */
    public void setTraindate(Date traindate) {
        this.traindate = traindate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TRA_SALE_ORDER_DETAIL.PREMIUM
     *
     * @return the value of TRA_SALE_ORDER_DETAIL.PREMIUM
     * @mbggenerated Mon Feb 27 15:21:11 CST 2017
     */
    public BigDecimal getPremium() {
        return premium;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TRA_SALE_ORDER_DETAIL.PREMIUM
     *
     * @param premium the value for TRA_SALE_ORDER_DETAIL.PREMIUM
     * @mbggenerated Mon Feb 27 15:21:11 CST 2017
     */
    public void setPremium(BigDecimal premium) {
        this.premium = premium;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TRA_SALE_ORDER_DETAIL.sale_price
     *
     * @return the value of TRA_SALE_ORDER_DETAIL.sale_price
     * @mbggenerated Mon Feb 27 15:21:11 CST 2017
     */
    public BigDecimal getSalePrice() {
        return salePrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TRA_SALE_ORDER_DETAIL.sale_price
     *
     * @param salePrice the value for TRA_SALE_ORDER_DETAIL.sale_price
     * @mbggenerated Mon Feb 27 15:21:11 CST 2017
     */
    public void setSalePrice(BigDecimal salePrice) {
        this.salePrice = salePrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TRA_SALE_ORDER_DETAIL.buy_price
     *
     * @return the value of TRA_SALE_ORDER_DETAIL.buy_price
     * @mbggenerated Mon Feb 27 15:21:11 CST 2017
     */
    public BigDecimal getBuyPrice() {
        return buyPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TRA_SALE_ORDER_DETAIL.buy_price
     *
     * @param buyPrice the value for TRA_SALE_ORDER_DETAIL.buy_price
     * @mbggenerated Mon Feb 27 15:21:11 CST 2017
     */
    public void setBuyPrice(BigDecimal buyPrice) {
        this.buyPrice = buyPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TRA_SALE_ORDER_DETAIL.SALE_ORDER_NO
     *
     * @return the value of TRA_SALE_ORDER_DETAIL.SALE_ORDER_NO
     * @mbggenerated Mon Feb 27 15:21:11 CST 2017
     */
    public Long getSaleOrderNo() {
        return saleOrderNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TRA_SALE_ORDER_DETAIL.SALE_ORDER_NO
     *
     * @param saleOrderNo the value for TRA_SALE_ORDER_DETAIL.SALE_ORDER_NO
     * @mbggenerated Mon Feb 27 15:21:11 CST 2017
     */
    public void setSaleOrderNo(Long saleOrderNo) {
        this.saleOrderNo = saleOrderNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TRA_SALE_ORDER_DETAIL.CREATE_TIME
     *
     * @return the value of TRA_SALE_ORDER_DETAIL.CREATE_TIME
     * @mbggenerated Mon Feb 27 15:21:11 CST 2017
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TRA_SALE_ORDER_DETAIL.CREATE_TIME
     *
     * @param createTime the value for TRA_SALE_ORDER_DETAIL.CREATE_TIME
     * @mbggenerated Mon Feb 27 15:21:11 CST 2017
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TRA_SALE_ORDER_DETAIL.MODIFY_TIME
     *
     * @return the value of TRA_SALE_ORDER_DETAIL.MODIFY_TIME
     * @mbggenerated Mon Feb 27 15:21:11 CST 2017
     */
    public Date getModifyTime() {
        return modifyTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TRA_SALE_ORDER_DETAIL.MODIFY_TIME
     *
     * @param modifyTime the value for TRA_SALE_ORDER_DETAIL.MODIFY_TIME
     * @mbggenerated Mon Feb 27 15:21:11 CST 2017
     */
    public void setModifyTime(Date modifyTime) {
        this.modifyTime = modifyTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TRA_SALE_ORDER_DETAIL.CREATOR
     *
     * @return the value of TRA_SALE_ORDER_DETAIL.CREATOR
     * @mbggenerated Mon Feb 27 15:21:11 CST 2017
     */
    public String getCreator() {
        return creator;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TRA_SALE_ORDER_DETAIL.CREATOR
     *
     * @param creator the value for TRA_SALE_ORDER_DETAIL.CREATOR
     * @mbggenerated Mon Feb 27 15:21:11 CST 2017
     */
    public void setCreator(String creator) {
        this.creator = creator == null ? null : creator.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TRA_SALE_ORDER_DETAIL.MODIFIER
     *
     * @return the value of TRA_SALE_ORDER_DETAIL.MODIFIER
     * @mbggenerated Mon Feb 27 15:21:11 CST 2017
     */
    public String getModifier() {
        return modifier;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TRA_SALE_ORDER_DETAIL.MODIFIER
     *
     * @param modifier the value for TRA_SALE_ORDER_DETAIL.MODIFIER
     * @mbggenerated Mon Feb 27 15:21:11 CST 2017
     */
    public void setModifier(String modifier) {
        this.modifier = modifier == null ? null : modifier.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TRA_SALE_ORDER_DETAIL.VALID
     *
     * @return the value of TRA_SALE_ORDER_DETAIL.VALID
     * @mbggenerated Mon Feb 27 15:21:11 CST 2017
     */
    public Boolean getValid() {
        return valid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TRA_SALE_ORDER_DETAIL.VALID
     *
     * @param valid the value for TRA_SALE_ORDER_DETAIL.VALID
     * @mbggenerated Mon Feb 27 15:21:11 CST 2017
     */
    public void setValid(Boolean valid) {
        this.valid = valid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TRA_SALE_ORDER_DETAIL.OWNER
     *
     * @return the value of TRA_SALE_ORDER_DETAIL.OWNER
     * @mbggenerated Mon Feb 27 15:21:11 CST 2017
     */
    public Integer getOwner() {
        return owner;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TRA_SALE_ORDER_DETAIL.OWNER
     *
     * @param owner the value for TRA_SALE_ORDER_DETAIL.OWNER
     * @mbggenerated Mon Feb 27 15:21:11 CST 2017
     */
    public void setOwner(Integer owner) {
        this.owner = owner;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TRA_SALE_ORDER_DETAIL.STATUS
     *
     * @return the value of TRA_SALE_ORDER_DETAIL.STATUS
     * @mbggenerated Mon Feb 27 15:21:11 CST 2017
     */
    public Integer getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TRA_SALE_ORDER_DETAIL.STATUS
     *
     * @param status the value for TRA_SALE_ORDER_DETAIL.STATUS
     * @mbggenerated Mon Feb 27 15:21:11 CST 2017
     */
    public void setStatus(Integer status) {
        this.status = status;
    }


    public TraPassenger getTraPassenger() {
        return traPassenger;
    }

    public void setTraPassenger(TraPassenger traPassenger) {
        this.traPassenger = traPassenger;
    }

    public String getOutPassengerNo() {
        return outPassengerNo;
    }

    public void setOutPassengerNo(String outPassengerNo) {
        this.outPassengerNo = outPassengerNo;
    }

    public String getSeatNo() {
        return seatNo;
    }

    public void setSeatNo(String seatNo) {
        this.seatNo = seatNo;
    }

    public Date getDepartureTime() {
        return departureTime;
    }

    public void setDepartureTime(Date departureTime) {
        this.departureTime = departureTime;
    }

    public Date getArrivalTime() {
        return arrivalTime;
    }

    public void setArrivalTime(Date arrivalTime) {
        this.arrivalTime = arrivalTime;
    }

    public BigDecimal getBrokerage() {
        return brokerage;
    }

    public void setBrokerage(BigDecimal brokerage) {
        this.brokerage = brokerage;
    }

    public BigDecimal getServiceFee() {
        return serviceFee;
    }

    public void setServiceFee(BigDecimal serviceFee) {
        this.serviceFee = serviceFee;
    }
}