package com.tempus.gss.product.tra.api.entity;


import com.fasterxml.jackson.databind.annotation.JsonSerialize;
import com.tempus.gss.order.entity.BuyOrder;
import com.tempus.gss.order.entity.SaleOrder;
import com.tempus.gss.serializer.LongSerializer;

import java.io.Serializable;
import java.math.BigDecimal;
import java.util.Date;
import java.util.List;

public class TraSaleOrderExt implements Serializable{
    public TraSaleOrderExt() {

    }
    /**
	 * 
	 */
	private static final long serialVersionUID = 1L;

	/**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TRA_SALE_ORDER_EXT.SALE_ORDER_NO
     *
     * @mbggenerated Sat Feb 25 17:24:56 CST 2017
     */
    @JsonSerialize(using = LongSerializer.class)
    private Long saleOrderNo;//销售单号

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TRA_SALE_ORDER_EXT.ID
     *
     * @mbggenerated Sat Feb 25 17:24:56 CST 2017
     */
    @JsonSerialize(using = LongSerializer.class)
    private Long id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TRA_SALE_ORDER_EXT.OWNER
     *
     * @mbggenerated Sat Feb 25 17:24:56 CST 2017
     */

    private Integer owner;//所有人

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TRA_SALE_ORDER_EXT.BUY_ORDER_NO
     *
     * @mbggenerated Sat Feb 25 17:24:56 CST 2017
     */
    @JsonSerialize(using = LongSerializer.class)
    private Long buyOrderNo;//采购单号

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TRA_SALE_ORDER_EXT.ORDER_NO
     *
     * @mbggenerated Sat Feb 25 17:24:56 CST 2017
     */
    @JsonSerialize(using = LongSerializer.class)
    private Long orderNo;//订单号

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TRA_SALE_ORDER_EXT.ORDER_TYPE
     *
     * @mbggenerated Sat Feb 25 17:24:56 CST 2017
     */
    private Integer orderType;//订单类型

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TRA_SALE_ORDER_EXT.person
     *
     * @mbggenerated Sat Feb 25 17:24:56 CST 2017
     */
    private String person;//订票人姓名

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TRA_SALE_ORDER_EXT.cellphone
     *
     * @mbggenerated Sat Feb 25 17:24:56 CST 2017
     */
    private String cellphone;//电话

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TRA_SALE_ORDER_EXT.email
     *
     * @mbggenerated Sat Feb 25 17:24:56 CST 2017
     */
    private String email;//订票人邮件

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TRA_SALE_ORDER_EXT.train_name
     *
     * @mbggenerated Sat Feb 25 17:24:56 CST 2017
     */
    private String trainName;//火车类型

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TRA_SALE_ORDER_EXT.SALE_PRICE
     *
     * @mbggenerated Sat Feb 25 17:24:56 CST 2017
     */
    private BigDecimal salePrice;//销售价

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TRA_SALE_ORDER_EXT.BUY_PRICE
     *
     * @mbggenerated Sat Feb 25 17:24:56 CST 2017
     */
    private BigDecimal buyPrice;//采购价

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TRA_SALE_ORDER_EXT.PREMIUM
     *
     * @mbggenerated Sat Feb 25 17:24:56 CST 2017
     */
    private BigDecimal premium;//总价

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TRA_SALE_ORDER_EXT.REMARK
     *
     * @mbggenerated Sat Feb 25 17:24:56 CST 2017
     */
    private String remark;//备注

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TRA_SALE_ORDER_EXT.IS_TEAM
     *
     * @mbggenerated Sat Feb 25 17:24:56 CST 2017
     */
    private Byte isTeam;//是否团队

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TRA_SALE_ORDER_EXT.SOURCE_NAME
     *
     * @mbggenerated Sat Feb 25 17:24:56 CST 2017
     */
    private String sourceName;//渠道名称

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TRA_SALE_ORDER_EXT.EXTENDED_FIELDS_JSON
     *
     * @mbggenerated Sat Feb 25 17:24:56 CST 2017
     */
    private String extendedFieldsJson;//扩展字段

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TRA_SALE_ORDER_EXT.CREATE_TIME
     *
     * @mbggenerated Sat Feb 25 17:24:56 CST 2017
     */
    private Date createTime;//创建时间

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TRA_SALE_ORDER_EXT.MODIFY_TIME
     *
     * @mbggenerated Sat Feb 25 17:24:56 CST 2017
     */
    private Date modifyTime;//修改时间

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TRA_SALE_ORDER_EXT.CREATOR
     *
     * @mbggenerated Sat Feb 25 17:24:56 CST 2017
     */
    private String creator;//创建人

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TRA_SALE_ORDER_EXT.MODIFIER
     *
     * @mbggenerated Sat Feb 25 17:24:56 CST 2017
     */
    private String modifier;//修改人

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TRA_SALE_ORDER_EXT.VALID
     *
     * @mbggenerated Sat Feb 25 17:24:56 CST 2017
     */
    private Boolean valid;//删除标志 0 无效 已删除 1 有效


    private SaleOrder saleOrder;//销售单


    private BuyOrder buyOrder;//采购单

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TRA_SALE_ORDER_EXT.ISSUE_DATE
     *
     * @mbggenerated Sat Feb 25 17:24:56 CST 2017
     */
    private Date issueDate;//买票时间


    private String outOrderNo;//外部订单号
    
    /**
     * 乘客姓
     */
    private String surname;
    
    /**
     * 乘客名
     */
    private String name;
    
    /**
     * 状态  1（已创建），2（支付中），3（出票中），4（已出票）5（退票中），
     * 6（改签中） 7（已退），8（已废），9（已改签），10（异常订单）
     */
    private int status;
    
    /**
     * 车次号
     */
    private String trainNo;
    
    /**
     * 发车时间
     */
    private Date departureTime;
    
    /**
     * 客商类型
     */
    private Long customerNo;
    
    /**
     * 客商编号
     */
    private Integer customerTypeNo;

    private List<TraSaleOrderDetail> saleOrderDetailList;//订单详情

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TRA_SALE_ORDER_EXT.SALE_ORDER_NO
     *
     * @return the value of TRA_SALE_ORDER_EXT.SALE_ORDER_NO
     *
     * @mbggenerated Sat Feb 25 17:24:56 CST 2017
     */
    public Long getSaleOrderNo() {
        return saleOrderNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TRA_SALE_ORDER_EXT.SALE_ORDER_NO
     *
     * @param saleOrderNo the value for TRA_SALE_ORDER_EXT.SALE_ORDER_NO
     *
     * @mbggenerated Sat Feb 25 17:24:56 CST 2017
     */
    public void setSaleOrderNo(Long saleOrderNo) {
        this.saleOrderNo = saleOrderNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TRA_SALE_ORDER_EXT.ID
     *
     * @return the value of TRA_SALE_ORDER_EXT.ID
     *
     * @mbggenerated Sat Feb 25 17:24:56 CST 2017
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TRA_SALE_ORDER_EXT.ID
     *
     * @param id the value for TRA_SALE_ORDER_EXT.ID
     *
     * @mbggenerated Sat Feb 25 17:24:56 CST 2017
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TRA_SALE_ORDER_EXT.OWNER
     *
     * @return the value of TRA_SALE_ORDER_EXT.OWNER
     *
     * @mbggenerated Sat Feb 25 17:24:56 CST 2017
     */
    public Integer getOwner() {
        return owner;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TRA_SALE_ORDER_EXT.OWNER
     *
     * @param owner the value for TRA_SALE_ORDER_EXT.OWNER
     *
     * @mbggenerated Sat Feb 25 17:24:56 CST 2017
     */
    public void setOwner(Integer owner) {
        this.owner = owner;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TRA_SALE_ORDER_EXT.BUY_ORDER_NO
     *
     * @return the value of TRA_SALE_ORDER_EXT.BUY_ORDER_NO
     *
     * @mbggenerated Sat Feb 25 17:24:56 CST 2017
     */
    public Long getBuyOrderNo() {
        return buyOrderNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TRA_SALE_ORDER_EXT.BUY_ORDER_NO
     *
     * @param buyOrderNo the value for TRA_SALE_ORDER_EXT.BUY_ORDER_NO
     *
     * @mbggenerated Sat Feb 25 17:24:56 CST 2017
     */
    public void setBuyOrderNo(Long buyOrderNo) {
        this.buyOrderNo = buyOrderNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TRA_SALE_ORDER_EXT.ORDER_NO
     *
     * @return the value of TRA_SALE_ORDER_EXT.ORDER_NO
     *
     * @mbggenerated Sat Feb 25 17:24:56 CST 2017
     */
    public Long getOrderNo() {
        return orderNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TRA_SALE_ORDER_EXT.ORDER_NO
     *
     * @param orderNo the value for TRA_SALE_ORDER_EXT.ORDER_NO
     *
     * @mbggenerated Sat Feb 25 17:24:56 CST 2017
     */
    public void setOrderNo(Long orderNo) {
        this.orderNo = orderNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TRA_SALE_ORDER_EXT.ORDER_TYPE
     *
     * @return the value of TRA_SALE_ORDER_EXT.ORDER_TYPE
     *
     * @mbggenerated Sat Feb 25 17:24:56 CST 2017
     */
    public Integer getOrderType() {
        return orderType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TRA_SALE_ORDER_EXT.ORDER_TYPE
     *
     * @param orderType the value for TRA_SALE_ORDER_EXT.ORDER_TYPE
     *
     * @mbggenerated Sat Feb 25 17:24:56 CST 2017
     */
    public void setOrderType(Integer orderType) {
        this.orderType = orderType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TRA_SALE_ORDER_EXT.person
     *
     * @return the value of TRA_SALE_ORDER_EXT.person
     *
     * @mbggenerated Sat Feb 25 17:24:56 CST 2017
     */
    public String getPerson() {
        return person;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TRA_SALE_ORDER_EXT.person
     *
     * @param person the value for TRA_SALE_ORDER_EXT.person
     *
     * @mbggenerated Sat Feb 25 17:24:56 CST 2017
     */
    public void setPerson(String person) {
        this.person = person == null ? null : person.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TRA_SALE_ORDER_EXT.cellphone
     *
     * @return the value of TRA_SALE_ORDER_EXT.cellphone
     *
     * @mbggenerated Sat Feb 25 17:24:56 CST 2017
     */
    public String getCellphone() {
        return cellphone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TRA_SALE_ORDER_EXT.cellphone
     *
     * @param cellphone the value for TRA_SALE_ORDER_EXT.cellphone
     *
     * @mbggenerated Sat Feb 25 17:24:56 CST 2017
     */
    public void setCellphone(String cellphone) {
        this.cellphone = cellphone == null ? null : cellphone.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TRA_SALE_ORDER_EXT.email
     *
     * @return the value of TRA_SALE_ORDER_EXT.email
     *
     * @mbggenerated Sat Feb 25 17:24:56 CST 2017
     */
    public String getEmail() {
        return email;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TRA_SALE_ORDER_EXT.email
     *
     * @param email the value for TRA_SALE_ORDER_EXT.email
     *
     * @mbggenerated Sat Feb 25 17:24:56 CST 2017
     */
    public void setEmail(String email) {
        this.email = email == null ? null : email.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TRA_SALE_ORDER_EXT.train_name
     *
     * @return the value of TRA_SALE_ORDER_EXT.train_name
     *
     * @mbggenerated Sat Feb 25 17:24:56 CST 2017
     */
    public String getTrainName() {
        return trainName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TRA_SALE_ORDER_EXT.train_name
     *
     * @param trainName the value for TRA_SALE_ORDER_EXT.train_name
     *
     * @mbggenerated Sat Feb 25 17:24:56 CST 2017
     */
    public void setTrainName(String trainName) {
        this.trainName = trainName == null ? null : trainName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TRA_SALE_ORDER_EXT.SALE_PRICE
     *
     * @return the value of TRA_SALE_ORDER_EXT.SALE_PRICE
     *
     * @mbggenerated Sat Feb 25 17:24:56 CST 2017
     */
    public BigDecimal getSalePrice() {
        return salePrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TRA_SALE_ORDER_EXT.SALE_PRICE
     *
     * @param salePrice the value for TRA_SALE_ORDER_EXT.SALE_PRICE
     *
     * @mbggenerated Sat Feb 25 17:24:56 CST 2017
     */
    public void setSalePrice(BigDecimal salePrice) {
        this.salePrice = salePrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TRA_SALE_ORDER_EXT.BUY_PRICE
     *
     * @return the value of TRA_SALE_ORDER_EXT.BUY_PRICE
     *
     * @mbggenerated Sat Feb 25 17:24:56 CST 2017
     */
    public BigDecimal getBuyPrice() {
        return buyPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TRA_SALE_ORDER_EXT.BUY_PRICE
     *
     * @param buyPrice the value for TRA_SALE_ORDER_EXT.BUY_PRICE
     *
     * @mbggenerated Sat Feb 25 17:24:56 CST 2017
     */
    public void setBuyPrice(BigDecimal buyPrice) {
        this.buyPrice = buyPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TRA_SALE_ORDER_EXT.PREMIUM
     *
     * @return the value of TRA_SALE_ORDER_EXT.PREMIUM
     *
     * @mbggenerated Sat Feb 25 17:24:56 CST 2017
     */
    public BigDecimal getPremium() {
        return premium;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TRA_SALE_ORDER_EXT.PREMIUM
     *
     * @param premium the value for TRA_SALE_ORDER_EXT.PREMIUM
     *
     * @mbggenerated Sat Feb 25 17:24:56 CST 2017
     */
    public void setPremium(BigDecimal premium) {
        this.premium = premium;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TRA_SALE_ORDER_EXT.REMARK
     *
     * @return the value of TRA_SALE_ORDER_EXT.REMARK
     *
     * @mbggenerated Sat Feb 25 17:24:56 CST 2017
     */
    public String getRemark() {
        return remark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TRA_SALE_ORDER_EXT.REMARK
     *
     * @param remark the value for TRA_SALE_ORDER_EXT.REMARK
     *
     * @mbggenerated Sat Feb 25 17:24:56 CST 2017
     */
    public void setRemark(String remark) {
        this.remark = remark == null ? null : remark.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TRA_SALE_ORDER_EXT.IS_TEAM
     *
     * @return the value of TRA_SALE_ORDER_EXT.IS_TEAM
     *
     * @mbggenerated Sat Feb 25 17:24:56 CST 2017
     */
    public Byte getIsTeam() {
        return isTeam;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TRA_SALE_ORDER_EXT.IS_TEAM
     *
     * @param isTeam the value for TRA_SALE_ORDER_EXT.IS_TEAM
     *
     * @mbggenerated Sat Feb 25 17:24:56 CST 2017
     */
    public void setIsTeam(Byte isTeam) {
        this.isTeam = isTeam;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TRA_SALE_ORDER_EXT.SOURCE_NAME
     *
     * @return the value of TRA_SALE_ORDER_EXT.SOURCE_NAME
     *
     * @mbggenerated Sat Feb 25 17:24:56 CST 2017
     */
    public String getSourceName() {
        return sourceName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TRA_SALE_ORDER_EXT.SOURCE_NAME
     *
     * @param sourceName the value for TRA_SALE_ORDER_EXT.SOURCE_NAME
     *
     * @mbggenerated Sat Feb 25 17:24:56 CST 2017
     */
    public void setSourceName(String sourceName) {
        this.sourceName = sourceName == null ? null : sourceName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TRA_SALE_ORDER_EXT.EXTENDED_FIELDS_JSON
     *
     * @return the value of TRA_SALE_ORDER_EXT.EXTENDED_FIELDS_JSON
     *
     * @mbggenerated Sat Feb 25 17:24:56 CST 2017
     */
    public String getExtendedFieldsJson() {
        return extendedFieldsJson;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TRA_SALE_ORDER_EXT.EXTENDED_FIELDS_JSON
     *
     * @param extendedFieldsJson the value for TRA_SALE_ORDER_EXT.EXTENDED_FIELDS_JSON
     *
     * @mbggenerated Sat Feb 25 17:24:56 CST 2017
     */
    public void setExtendedFieldsJson(String extendedFieldsJson) {
        this.extendedFieldsJson = extendedFieldsJson == null ? null : extendedFieldsJson.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TRA_SALE_ORDER_EXT.CREATE_TIME
     *
     * @return the value of TRA_SALE_ORDER_EXT.CREATE_TIME
     *
     * @mbggenerated Sat Feb 25 17:24:56 CST 2017
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TRA_SALE_ORDER_EXT.CREATE_TIME
     *
     * @param createTime the value for TRA_SALE_ORDER_EXT.CREATE_TIME
     *
     * @mbggenerated Sat Feb 25 17:24:56 CST 2017
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TRA_SALE_ORDER_EXT.MODIFY_TIME
     *
     * @return the value of TRA_SALE_ORDER_EXT.MODIFY_TIME
     *
     * @mbggenerated Sat Feb 25 17:24:56 CST 2017
     */
    public Date getModifyTime() {
        return modifyTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TRA_SALE_ORDER_EXT.MODIFY_TIME
     *
     * @param modifyTime the value for TRA_SALE_ORDER_EXT.MODIFY_TIME
     *
     * @mbggenerated Sat Feb 25 17:24:56 CST 2017
     */
    public void setModifyTime(Date modifyTime) {
        this.modifyTime = modifyTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TRA_SALE_ORDER_EXT.CREATOR
     *
     * @return the value of TRA_SALE_ORDER_EXT.CREATOR
     *
     * @mbggenerated Sat Feb 25 17:24:56 CST 2017
     */
    public String getCreator() {
        return creator;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TRA_SALE_ORDER_EXT.CREATOR
     *
     * @param creator the value for TRA_SALE_ORDER_EXT.CREATOR
     *
     * @mbggenerated Sat Feb 25 17:24:56 CST 2017
     */
    public void setCreator(String creator) {
        this.creator = creator == null ? null : creator.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TRA_SALE_ORDER_EXT.MODIFIER
     *
     * @return the value of TRA_SALE_ORDER_EXT.MODIFIER
     *
     * @mbggenerated Sat Feb 25 17:24:56 CST 2017
     */
    public String getModifier() {
        return modifier;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TRA_SALE_ORDER_EXT.MODIFIER
     *
     * @param modifier the value for TRA_SALE_ORDER_EXT.MODIFIER
     *
     * @mbggenerated Sat Feb 25 17:24:56 CST 2017
     */
    public void setModifier(String modifier) {
        this.modifier = modifier == null ? null : modifier.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TRA_SALE_ORDER_EXT.VALID
     *
     * @return the value of TRA_SALE_ORDER_EXT.VALID
     *
     * @mbggenerated Sat Feb 25 17:24:56 CST 2017
     */
    public Boolean getValid() {
        return valid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TRA_SALE_ORDER_EXT.VALID
     *
     * @param valid the value for TRA_SALE_ORDER_EXT.VALID
     *
     * @mbggenerated Sat Feb 25 17:24:56 CST 2017
     */
    public void setValid(Boolean valid) {
        this.valid = valid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TRA_SALE_ORDER_EXT.ISSUE_DATE
     *
     * @return the value of TRA_SALE_ORDER_EXT.ISSUE_DATE
     *
     * @mbggenerated Sat Feb 25 17:24:56 CST 2017
     */
    public Date getIssueDate() {
        return issueDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TRA_SALE_ORDER_EXT.ISSUE_DATE
     *
     * @param issueDate the value for TRA_SALE_ORDER_EXT.ISSUE_DATE
     *
     * @mbggenerated Sat Feb 25 17:24:56 CST 2017
     */
    public void setIssueDate(Date issueDate) {
        this.issueDate = issueDate;
    }

    public SaleOrder getSaleOrder() {
        return saleOrder;
    }

    public void setSaleOrder(SaleOrder saleOrder) {
        this.saleOrder = saleOrder;
    }

    public BuyOrder getBuyOrder() {
        return buyOrder;
    }

    public void setBuyOrder(BuyOrder buyOrder) {
        this.buyOrder = buyOrder;
    }

    public List<TraSaleOrderDetail> getSaleOrderDetailList() {
        return saleOrderDetailList;
    }

    public void setSaleOrderDetailList(List<TraSaleOrderDetail> saleOrderDetailList) {
        this.saleOrderDetailList = saleOrderDetailList;
    }

    public String getOutOrderNo() {
        return outOrderNo;
    }

    public void setOutOrderNo(String outOrderNo) {
        this.outOrderNo = outOrderNo;
    }

	public String getSurname() {
		return surname;
	}

	public void setSurname(String surname) {
		this.surname = surname;
	}

	public String getName() {
		return name;
	}

	public void setName(String name) {
		this.name = name;
	}

	public int getStatus() {
		return status;
	}

	public void setStatus(int status) {
		this.status = status;
	}

	public String getTrainNo() {
		return trainNo;
	}

	public void setTrainNo(String trainNo) {
		this.trainNo = trainNo;
	}

	public Date getDepartureTime() {
		return departureTime;
	}

	public void setDepartureTime(Date departureTime) {
		this.departureTime = departureTime;
	}

	public Long getCustomerNo() {
		return customerNo;
	}

	public void setCustomerNo(Long customerNo) {
		this.customerNo = customerNo;
	}

	public Integer getCustomerTypeNo() {
		return customerTypeNo;
	}

	public void setCustomerTypeNo(Integer customerTypeNo) {
		this.customerTypeNo = customerTypeNo;
	}
    
    
}