package com.tempus.gss.product.tra.api.entity;

import java.io.Serializable;
import java.util.Date;

public class TraSupplier  implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TRA_SUPPLIER.SUPPLIER_NO
     *
     * @mbggenerated Fri Feb 24 15:34:26 CST 2017
     */
    private Long supplierNo;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TRA_SUPPLIER.ID
     *
     * @mbggenerated Fri Feb 24 15:34:26 CST 2017
     */
    private Long id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TRA_SUPPLIER.VALID
     *
     * @mbggenerated Fri Feb 24 15:34:26 CST 2017
     */
    private Byte valid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TRA_SUPPLIER.STATUS
     *
     * @mbggenerated Fri Feb 24 15:34:26 CST 2017
     */
    private Integer status;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TRA_SUPPLIER.CAPITAL_ACCOUNT_NO
     *
     * @mbggenerated Fri Feb 24 15:34:26 CST 2017
     */
    private Long capitalAccountNo;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TRA_SUPPLIER.ACCOUNT_NO
     *
     * @mbggenerated Fri Feb 24 15:34:26 CST 2017
     */
    private Long accountNo;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TRA_SUPPLIER.CREATOR
     *
     * @mbggenerated Fri Feb 24 15:34:26 CST 2017
     */
    private String creator;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TRA_SUPPLIER.CREATE_TIME
     *
     * @mbggenerated Fri Feb 24 15:34:26 CST 2017
     */
    private Date createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TRA_SUPPLIER.SORT
     *
     * @mbggenerated Fri Feb 24 15:34:26 CST 2017
     */
    private Long sort;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TRA_SUPPLIER.SUPPLIER_NO
     *
     * @return the value of TRA_SUPPLIER.SUPPLIER_NO
     *
     * @mbggenerated Fri Feb 24 15:34:26 CST 2017
     */
    public Long getSupplierNo() {
        return supplierNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TRA_SUPPLIER.SUPPLIER_NO
     *
     * @param supplierNo the value for TRA_SUPPLIER.SUPPLIER_NO
     *
     * @mbggenerated Fri Feb 24 15:34:26 CST 2017
     */
    public void setSupplierNo(Long supplierNo) {
        this.supplierNo = supplierNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TRA_SUPPLIER.ID
     *
     * @return the value of TRA_SUPPLIER.ID
     *
     * @mbggenerated Fri Feb 24 15:34:26 CST 2017
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TRA_SUPPLIER.ID
     *
     * @param id the value for TRA_SUPPLIER.ID
     *
     * @mbggenerated Fri Feb 24 15:34:26 CST 2017
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TRA_SUPPLIER.VALID
     *
     * @return the value of TRA_SUPPLIER.VALID
     *
     * @mbggenerated Fri Feb 24 15:34:26 CST 2017
     */
    public Byte getValid() {
        return valid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TRA_SUPPLIER.VALID
     *
     * @param valid the value for TRA_SUPPLIER.VALID
     *
     * @mbggenerated Fri Feb 24 15:34:26 CST 2017
     */
    public void setValid(Byte valid) {
        this.valid = valid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TRA_SUPPLIER.STATUS
     *
     * @return the value of TRA_SUPPLIER.STATUS
     *
     * @mbggenerated Fri Feb 24 15:34:26 CST 2017
     */
    public Integer getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TRA_SUPPLIER.STATUS
     *
     * @param status the value for TRA_SUPPLIER.STATUS
     *
     * @mbggenerated Fri Feb 24 15:34:26 CST 2017
     */
    public void setStatus(Integer status) {
        this.status = status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TRA_SUPPLIER.CAPITAL_ACCOUNT_NO
     *
     * @return the value of TRA_SUPPLIER.CAPITAL_ACCOUNT_NO
     *
     * @mbggenerated Fri Feb 24 15:34:26 CST 2017
     */
    public Long getCapitalAccountNo() {
        return capitalAccountNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TRA_SUPPLIER.CAPITAL_ACCOUNT_NO
     *
     * @param capitalAccountNo the value for TRA_SUPPLIER.CAPITAL_ACCOUNT_NO
     *
     * @mbggenerated Fri Feb 24 15:34:26 CST 2017
     */
    public void setCapitalAccountNo(Long capitalAccountNo) {
        this.capitalAccountNo = capitalAccountNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TRA_SUPPLIER.ACCOUNT_NO
     *
     * @return the value of TRA_SUPPLIER.ACCOUNT_NO
     *
     * @mbggenerated Fri Feb 24 15:34:26 CST 2017
     */
    public Long getAccountNo() {
        return accountNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TRA_SUPPLIER.ACCOUNT_NO
     *
     * @param accountNo the value for TRA_SUPPLIER.ACCOUNT_NO
     *
     * @mbggenerated Fri Feb 24 15:34:26 CST 2017
     */
    public void setAccountNo(Long accountNo) {
        this.accountNo = accountNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TRA_SUPPLIER.CREATOR
     *
     * @return the value of TRA_SUPPLIER.CREATOR
     *
     * @mbggenerated Fri Feb 24 15:34:26 CST 2017
     */
    public String getCreator() {
        return creator;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TRA_SUPPLIER.CREATOR
     *
     * @param creator the value for TRA_SUPPLIER.CREATOR
     *
     * @mbggenerated Fri Feb 24 15:34:26 CST 2017
     */
    public void setCreator(String creator) {
        this.creator = creator == null ? null : creator.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TRA_SUPPLIER.CREATE_TIME
     *
     * @return the value of TRA_SUPPLIER.CREATE_TIME
     *
     * @mbggenerated Fri Feb 24 15:34:26 CST 2017
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TRA_SUPPLIER.CREATE_TIME
     *
     * @param createTime the value for TRA_SUPPLIER.CREATE_TIME
     *
     * @mbggenerated Fri Feb 24 15:34:26 CST 2017
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TRA_SUPPLIER.SORT
     *
     * @return the value of TRA_SUPPLIER.SORT
     *
     * @mbggenerated Fri Feb 24 15:34:26 CST 2017
     */
    public Long getSort() {
        return sort;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TRA_SUPPLIER.SORT
     *
     * @param sort the value for TRA_SUPPLIER.SORT
     *
     * @mbggenerated Fri Feb 24 15:34:26 CST 2017
     */
    public void setSort(Long sort) {
        this.sort = sort;
    }
}