package com.tempus.gss.product.tra.api.entity;

import java.math.BigDecimal;
import java.util.ArrayList;
import java.util.Date;
import java.util.List;

public class TraSaleOrderDetailExample  {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table TRA_SALE_ORDER_DETAIL
     *
     * @mbggenerated Mon Feb 27 15:21:11 CST 2017
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table TRA_SALE_ORDER_DETAIL
     *
     * @mbggenerated Mon Feb 27 15:21:11 CST 2017
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table TRA_SALE_ORDER_DETAIL
     *
     * @mbggenerated Mon Feb 27 15:21:11 CST 2017
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TRA_SALE_ORDER_DETAIL
     *
     * @mbggenerated Mon Feb 27 15:21:11 CST 2017
     */
    public TraSaleOrderDetailExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TRA_SALE_ORDER_DETAIL
     *
     * @mbggenerated Mon Feb 27 15:21:11 CST 2017
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TRA_SALE_ORDER_DETAIL
     *
     * @mbggenerated Mon Feb 27 15:21:11 CST 2017
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TRA_SALE_ORDER_DETAIL
     *
     * @mbggenerated Mon Feb 27 15:21:11 CST 2017
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TRA_SALE_ORDER_DETAIL
     *
     * @mbggenerated Mon Feb 27 15:21:11 CST 2017
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TRA_SALE_ORDER_DETAIL
     *
     * @mbggenerated Mon Feb 27 15:21:11 CST 2017
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TRA_SALE_ORDER_DETAIL
     *
     * @mbggenerated Mon Feb 27 15:21:11 CST 2017
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TRA_SALE_ORDER_DETAIL
     *
     * @mbggenerated Mon Feb 27 15:21:11 CST 2017
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TRA_SALE_ORDER_DETAIL
     *
     * @mbggenerated Mon Feb 27 15:21:11 CST 2017
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TRA_SALE_ORDER_DETAIL
     *
     * @mbggenerated Mon Feb 27 15:21:11 CST 2017
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TRA_SALE_ORDER_DETAIL
     *
     * @mbggenerated Mon Feb 27 15:21:11 CST 2017
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table TRA_SALE_ORDER_DETAIL
     *
     * @mbggenerated Mon Feb 27 15:21:11 CST 2017
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andSaleOrderDetailNoIsNull() {
            addCriterion("SALE_ORDER_DETAIL_NO is null");
            return (Criteria) this;
        }

        public Criteria andSaleOrderDetailNoIsNotNull() {
            addCriterion("SALE_ORDER_DETAIL_NO is not null");
            return (Criteria) this;
        }

        public Criteria andSaleOrderDetailNoEqualTo(Long value) {
            addCriterion("SALE_ORDER_DETAIL_NO =", value, "saleOrderDetailNo");
            return (Criteria) this;
        }

        public Criteria andSaleOrderDetailNoNotEqualTo(Long value) {
            addCriterion("SALE_ORDER_DETAIL_NO <>", value, "saleOrderDetailNo");
            return (Criteria) this;
        }

        public Criteria andSaleOrderDetailNoGreaterThan(Long value) {
            addCriterion("SALE_ORDER_DETAIL_NO >", value, "saleOrderDetailNo");
            return (Criteria) this;
        }

        public Criteria andSaleOrderDetailNoGreaterThanOrEqualTo(Long value) {
            addCriterion("SALE_ORDER_DETAIL_NO >=", value, "saleOrderDetailNo");
            return (Criteria) this;
        }

        public Criteria andSaleOrderDetailNoLessThan(Long value) {
            addCriterion("SALE_ORDER_DETAIL_NO <", value, "saleOrderDetailNo");
            return (Criteria) this;
        }

        public Criteria andSaleOrderDetailNoLessThanOrEqualTo(Long value) {
            addCriterion("SALE_ORDER_DETAIL_NO <=", value, "saleOrderDetailNo");
            return (Criteria) this;
        }

        public Criteria andSaleOrderDetailNoIn(List<Long> values) {
            addCriterion("SALE_ORDER_DETAIL_NO in", values, "saleOrderDetailNo");
            return (Criteria) this;
        }

        public Criteria andSaleOrderDetailNoNotIn(List<Long> values) {
            addCriterion("SALE_ORDER_DETAIL_NO not in", values, "saleOrderDetailNo");
            return (Criteria) this;
        }

        public Criteria andSaleOrderDetailNoBetween(Long value1, Long value2) {
            addCriterion("SALE_ORDER_DETAIL_NO between", value1, value2, "saleOrderDetailNo");
            return (Criteria) this;
        }

        public Criteria andSaleOrderDetailNoNotBetween(Long value1, Long value2) {
            addCriterion("SALE_ORDER_DETAIL_NO not between", value1, value2, "saleOrderDetailNo");
            return (Criteria) this;
        }

        public Criteria andIdIsNull() {
            addCriterion("id is null");
            return (Criteria) this;
        }

        public Criteria andIdIsNotNull() {
            addCriterion("id is not null");
            return (Criteria) this;
        }

        public Criteria andIdEqualTo(String value) {
            addCriterion("id =", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotEqualTo(String value) {
            addCriterion("id <>", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThan(String value) {
            addCriterion("id >", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThanOrEqualTo(String value) {
            addCriterion("id >=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThan(String value) {
            addCriterion("id <", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThanOrEqualTo(String value) {
            addCriterion("id <=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLike(String value) {
            addCriterion("id like", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotLike(String value) {
            addCriterion("id not like", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdIn(List<String> values) {
            addCriterion("id in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotIn(List<String> values) {
            addCriterion("id not in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdBetween(String value1, String value2) {
            addCriterion("id between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotBetween(String value1, String value2) {
            addCriterion("id not between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andPassengerNoIsNull() {
            addCriterion("passenger_no is null");
            return (Criteria) this;
        }

        public Criteria andPassengerNoIsNotNull() {
            addCriterion("passenger_no is not null");
            return (Criteria) this;
        }

        public Criteria andPassengerNoEqualTo(Long value) {
            addCriterion("passenger_no =", value, "passengerNo");
            return (Criteria) this;
        }

        public Criteria andPassengerNoNotEqualTo(Long value) {
            addCriterion("passenger_no <>", value, "passengerNo");
            return (Criteria) this;
        }

        public Criteria andPassengerNoGreaterThan(Long value) {
            addCriterion("passenger_no >", value, "passengerNo");
            return (Criteria) this;
        }

        public Criteria andPassengerNoGreaterThanOrEqualTo(Long value) {
            addCriterion("passenger_no >=", value, "passengerNo");
            return (Criteria) this;
        }

        public Criteria andPassengerNoLessThan(Long value) {
            addCriterion("passenger_no <", value, "passengerNo");
            return (Criteria) this;
        }

        public Criteria andPassengerNoLessThanOrEqualTo(Long value) {
            addCriterion("passenger_no <=", value, "passengerNo");
            return (Criteria) this;
        }

        public Criteria andPassengerNoIn(List<Long> values) {
            addCriterion("passenger_no in", values, "passengerNo");
            return (Criteria) this;
        }

        public Criteria andPassengerNoNotIn(List<Long> values) {
            addCriterion("passenger_no not in", values, "passengerNo");
            return (Criteria) this;
        }

        public Criteria andPassengerNoBetween(Long value1, Long value2) {
            addCriterion("passenger_no between", value1, value2, "passengerNo");
            return (Criteria) this;
        }

        public Criteria andPassengerNoNotBetween(Long value1, Long value2) {
            addCriterion("passenger_no not between", value1, value2, "passengerNo");
            return (Criteria) this;
        }

        public Criteria andTrainnoIsNull() {
            addCriterion("trainNo is null");
            return (Criteria) this;
        }

        public Criteria andTrainnoIsNotNull() {
            addCriterion("trainNo is not null");
            return (Criteria) this;
        }

        public Criteria andTrainnoEqualTo(String value) {
            addCriterion("trainNo =", value, "trainno");
            return (Criteria) this;
        }

        public Criteria andTrainnoNotEqualTo(String value) {
            addCriterion("trainNo <>", value, "trainno");
            return (Criteria) this;
        }

        public Criteria andTrainnoGreaterThan(String value) {
            addCriterion("trainNo >", value, "trainno");
            return (Criteria) this;
        }

        public Criteria andTrainnoGreaterThanOrEqualTo(String value) {
            addCriterion("trainNo >=", value, "trainno");
            return (Criteria) this;
        }

        public Criteria andTrainnoLessThan(String value) {
            addCriterion("trainNo <", value, "trainno");
            return (Criteria) this;
        }

        public Criteria andTrainnoLessThanOrEqualTo(String value) {
            addCriterion("trainNo <=", value, "trainno");
            return (Criteria) this;
        }

        public Criteria andTrainnoLike(String value) {
            addCriterion("trainNo like", value, "trainno");
            return (Criteria) this;
        }

        public Criteria andTrainnoNotLike(String value) {
            addCriterion("trainNo not like", value, "trainno");
            return (Criteria) this;
        }

        public Criteria andTrainnoIn(List<String> values) {
            addCriterion("trainNo in", values, "trainno");
            return (Criteria) this;
        }

        public Criteria andTrainnoNotIn(List<String> values) {
            addCriterion("trainNo not in", values, "trainno");
            return (Criteria) this;
        }

        public Criteria andTrainnoBetween(String value1, String value2) {
            addCriterion("trainNo between", value1, value2, "trainno");
            return (Criteria) this;
        }

        public Criteria andTrainnoNotBetween(String value1, String value2) {
            addCriterion("trainNo not between", value1, value2, "trainno");
            return (Criteria) this;
        }

        public Criteria andSeatclassIsNull() {
            addCriterion("seatClass is null");
            return (Criteria) this;
        }

        public Criteria andSeatclassIsNotNull() {
            addCriterion("seatClass is not null");
            return (Criteria) this;
        }

        public Criteria andSeatclassEqualTo(Byte value) {
            addCriterion("seatClass =", value, "seatclass");
            return (Criteria) this;
        }

        public Criteria andSeatclassNotEqualTo(Byte value) {
            addCriterion("seatClass <>", value, "seatclass");
            return (Criteria) this;
        }

        public Criteria andSeatclassGreaterThan(Byte value) {
            addCriterion("seatClass >", value, "seatclass");
            return (Criteria) this;
        }

        public Criteria andSeatclassGreaterThanOrEqualTo(Byte value) {
            addCriterion("seatClass >=", value, "seatclass");
            return (Criteria) this;
        }

        public Criteria andSeatclassLessThan(Byte value) {
            addCriterion("seatClass <", value, "seatclass");
            return (Criteria) this;
        }

        public Criteria andSeatclassLessThanOrEqualTo(Byte value) {
            addCriterion("seatClass <=", value, "seatclass");
            return (Criteria) this;
        }

        public Criteria andSeatclassIn(List<Byte> values) {
            addCriterion("seatClass in", values, "seatclass");
            return (Criteria) this;
        }

        public Criteria andSeatclassNotIn(List<Byte> values) {
            addCriterion("seatClass not in", values, "seatclass");
            return (Criteria) this;
        }

        public Criteria andSeatclassBetween(Byte value1, Byte value2) {
            addCriterion("seatClass between", value1, value2, "seatclass");
            return (Criteria) this;
        }

        public Criteria andSeatclassNotBetween(Byte value1, Byte value2) {
            addCriterion("seatClass not between", value1, value2, "seatclass");
            return (Criteria) this;
        }

        public Criteria andFromstationIsNull() {
            addCriterion("fromStation is null");
            return (Criteria) this;
        }

        public Criteria andFromstationIsNotNull() {
            addCriterion("fromStation is not null");
            return (Criteria) this;
        }

        public Criteria andFromstationEqualTo(String value) {
            addCriterion("fromStation =", value, "fromstation");
            return (Criteria) this;
        }

        public Criteria andFromstationNotEqualTo(String value) {
            addCriterion("fromStation <>", value, "fromstation");
            return (Criteria) this;
        }

        public Criteria andFromstationGreaterThan(String value) {
            addCriterion("fromStation >", value, "fromstation");
            return (Criteria) this;
        }

        public Criteria andFromstationGreaterThanOrEqualTo(String value) {
            addCriterion("fromStation >=", value, "fromstation");
            return (Criteria) this;
        }

        public Criteria andFromstationLessThan(String value) {
            addCriterion("fromStation <", value, "fromstation");
            return (Criteria) this;
        }

        public Criteria andFromstationLessThanOrEqualTo(String value) {
            addCriterion("fromStation <=", value, "fromstation");
            return (Criteria) this;
        }

        public Criteria andFromstationLike(String value) {
            addCriterion("fromStation like", value, "fromstation");
            return (Criteria) this;
        }

        public Criteria andFromstationNotLike(String value) {
            addCriterion("fromStation not like", value, "fromstation");
            return (Criteria) this;
        }

        public Criteria andFromstationIn(List<String> values) {
            addCriterion("fromStation in", values, "fromstation");
            return (Criteria) this;
        }

        public Criteria andFromstationNotIn(List<String> values) {
            addCriterion("fromStation not in", values, "fromstation");
            return (Criteria) this;
        }

        public Criteria andFromstationBetween(String value1, String value2) {
            addCriterion("fromStation between", value1, value2, "fromstation");
            return (Criteria) this;
        }

        public Criteria andFromstationNotBetween(String value1, String value2) {
            addCriterion("fromStation not between", value1, value2, "fromstation");
            return (Criteria) this;
        }

        public Criteria andTostationIsNull() {
            addCriterion("toStation is null");
            return (Criteria) this;
        }

        public Criteria andTostationIsNotNull() {
            addCriterion("toStation is not null");
            return (Criteria) this;
        }

        public Criteria andTostationEqualTo(String value) {
            addCriterion("toStation =", value, "tostation");
            return (Criteria) this;
        }

        public Criteria andTostationNotEqualTo(String value) {
            addCriterion("toStation <>", value, "tostation");
            return (Criteria) this;
        }

        public Criteria andTostationGreaterThan(String value) {
            addCriterion("toStation >", value, "tostation");
            return (Criteria) this;
        }

        public Criteria andTostationGreaterThanOrEqualTo(String value) {
            addCriterion("toStation >=", value, "tostation");
            return (Criteria) this;
        }

        public Criteria andTostationLessThan(String value) {
            addCriterion("toStation <", value, "tostation");
            return (Criteria) this;
        }

        public Criteria andTostationLessThanOrEqualTo(String value) {
            addCriterion("toStation <=", value, "tostation");
            return (Criteria) this;
        }

        public Criteria andTostationLike(String value) {
            addCriterion("toStation like", value, "tostation");
            return (Criteria) this;
        }

        public Criteria andTostationNotLike(String value) {
            addCriterion("toStation not like", value, "tostation");
            return (Criteria) this;
        }

        public Criteria andTostationIn(List<String> values) {
            addCriterion("toStation in", values, "tostation");
            return (Criteria) this;
        }

        public Criteria andTostationNotIn(List<String> values) {
            addCriterion("toStation not in", values, "tostation");
            return (Criteria) this;
        }

        public Criteria andTostationBetween(String value1, String value2) {
            addCriterion("toStation between", value1, value2, "tostation");
            return (Criteria) this;
        }

        public Criteria andTostationNotBetween(String value1, String value2) {
            addCriterion("toStation not between", value1, value2, "tostation");
            return (Criteria) this;
        }

        public Criteria andTraindateIsNull() {
            addCriterion("trainDate is null");
            return (Criteria) this;
        }

        public Criteria andTraindateIsNotNull() {
            addCriterion("trainDate is not null");
            return (Criteria) this;
        }

        public Criteria andTraindateEqualTo(Date value) {
            addCriterion("trainDate =", value, "traindate");
            return (Criteria) this;
        }

        public Criteria andTraindateNotEqualTo(Date value) {
            addCriterion("trainDate <>", value, "traindate");
            return (Criteria) this;
        }

        public Criteria andTraindateGreaterThan(Date value) {
            addCriterion("trainDate >", value, "traindate");
            return (Criteria) this;
        }

        public Criteria andTraindateGreaterThanOrEqualTo(Date value) {
            addCriterion("trainDate >=", value, "traindate");
            return (Criteria) this;
        }

        public Criteria andTraindateLessThan(Date value) {
            addCriterion("trainDate <", value, "traindate");
            return (Criteria) this;
        }

        public Criteria andTraindateLessThanOrEqualTo(Date value) {
            addCriterion("trainDate <=", value, "traindate");
            return (Criteria) this;
        }

        public Criteria andTraindateIn(List<Date> values) {
            addCriterion("trainDate in", values, "traindate");
            return (Criteria) this;
        }

        public Criteria andTraindateNotIn(List<Date> values) {
            addCriterion("trainDate not in", values, "traindate");
            return (Criteria) this;
        }

        public Criteria andTraindateBetween(Date value1, Date value2) {
            addCriterion("trainDate between", value1, value2, "traindate");
            return (Criteria) this;
        }

        public Criteria andTraindateNotBetween(Date value1, Date value2) {
            addCriterion("trainDate not between", value1, value2, "traindate");
            return (Criteria) this;
        }

        public Criteria andPremiumIsNull() {
            addCriterion("PREMIUM is null");
            return (Criteria) this;
        }

        public Criteria andPremiumIsNotNull() {
            addCriterion("PREMIUM is not null");
            return (Criteria) this;
        }

        public Criteria andPremiumEqualTo(BigDecimal value) {
            addCriterion("PREMIUM =", value, "premium");
            return (Criteria) this;
        }

        public Criteria andPremiumNotEqualTo(BigDecimal value) {
            addCriterion("PREMIUM <>", value, "premium");
            return (Criteria) this;
        }

        public Criteria andPremiumGreaterThan(BigDecimal value) {
            addCriterion("PREMIUM >", value, "premium");
            return (Criteria) this;
        }

        public Criteria andPremiumGreaterThanOrEqualTo(BigDecimal value) {
            addCriterion("PREMIUM >=", value, "premium");
            return (Criteria) this;
        }

        public Criteria andPremiumLessThan(BigDecimal value) {
            addCriterion("PREMIUM <", value, "premium");
            return (Criteria) this;
        }

        public Criteria andPremiumLessThanOrEqualTo(BigDecimal value) {
            addCriterion("PREMIUM <=", value, "premium");
            return (Criteria) this;
        }

        public Criteria andPremiumIn(List<BigDecimal> values) {
            addCriterion("PREMIUM in", values, "premium");
            return (Criteria) this;
        }

        public Criteria andPremiumNotIn(List<BigDecimal> values) {
            addCriterion("PREMIUM not in", values, "premium");
            return (Criteria) this;
        }

        public Criteria andPremiumBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("PREMIUM between", value1, value2, "premium");
            return (Criteria) this;
        }

        public Criteria andPremiumNotBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("PREMIUM not between", value1, value2, "premium");
            return (Criteria) this;
        }

        public Criteria andSalePriceIsNull() {
            addCriterion("sale_price is null");
            return (Criteria) this;
        }

        public Criteria andSalePriceIsNotNull() {
            addCriterion("sale_price is not null");
            return (Criteria) this;
        }

        public Criteria andSalePriceEqualTo(BigDecimal value) {
            addCriterion("sale_price =", value, "salePrice");
            return (Criteria) this;
        }

        public Criteria andSalePriceNotEqualTo(BigDecimal value) {
            addCriterion("sale_price <>", value, "salePrice");
            return (Criteria) this;
        }

        public Criteria andSalePriceGreaterThan(BigDecimal value) {
            addCriterion("sale_price >", value, "salePrice");
            return (Criteria) this;
        }

        public Criteria andSalePriceGreaterThanOrEqualTo(BigDecimal value) {
            addCriterion("sale_price >=", value, "salePrice");
            return (Criteria) this;
        }

        public Criteria andSalePriceLessThan(BigDecimal value) {
            addCriterion("sale_price <", value, "salePrice");
            return (Criteria) this;
        }

        public Criteria andSalePriceLessThanOrEqualTo(BigDecimal value) {
            addCriterion("sale_price <=", value, "salePrice");
            return (Criteria) this;
        }

        public Criteria andSalePriceIn(List<BigDecimal> values) {
            addCriterion("sale_price in", values, "salePrice");
            return (Criteria) this;
        }

        public Criteria andSalePriceNotIn(List<BigDecimal> values) {
            addCriterion("sale_price not in", values, "salePrice");
            return (Criteria) this;
        }

        public Criteria andSalePriceBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("sale_price between", value1, value2, "salePrice");
            return (Criteria) this;
        }

        public Criteria andSalePriceNotBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("sale_price not between", value1, value2, "salePrice");
            return (Criteria) this;
        }

        public Criteria andBuyPriceIsNull() {
            addCriterion("buy_price is null");
            return (Criteria) this;
        }

        public Criteria andBuyPriceIsNotNull() {
            addCriterion("buy_price is not null");
            return (Criteria) this;
        }

        public Criteria andBuyPriceEqualTo(BigDecimal value) {
            addCriterion("buy_price =", value, "buyPrice");
            return (Criteria) this;
        }

        public Criteria andBuyPriceNotEqualTo(BigDecimal value) {
            addCriterion("buy_price <>", value, "buyPrice");
            return (Criteria) this;
        }

        public Criteria andBuyPriceGreaterThan(BigDecimal value) {
            addCriterion("buy_price >", value, "buyPrice");
            return (Criteria) this;
        }

        public Criteria andBuyPriceGreaterThanOrEqualTo(BigDecimal value) {
            addCriterion("buy_price >=", value, "buyPrice");
            return (Criteria) this;
        }

        public Criteria andBuyPriceLessThan(BigDecimal value) {
            addCriterion("buy_price <", value, "buyPrice");
            return (Criteria) this;
        }

        public Criteria andBuyPriceLessThanOrEqualTo(BigDecimal value) {
            addCriterion("buy_price <=", value, "buyPrice");
            return (Criteria) this;
        }

        public Criteria andBuyPriceIn(List<BigDecimal> values) {
            addCriterion("buy_price in", values, "buyPrice");
            return (Criteria) this;
        }

        public Criteria andBuyPriceNotIn(List<BigDecimal> values) {
            addCriterion("buy_price not in", values, "buyPrice");
            return (Criteria) this;
        }

        public Criteria andBuyPriceBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("buy_price between", value1, value2, "buyPrice");
            return (Criteria) this;
        }

        public Criteria andBuyPriceNotBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("buy_price not between", value1, value2, "buyPrice");
            return (Criteria) this;
        }

        public Criteria andSaleOrderNoIsNull() {
            addCriterion("SALE_ORDER_NO is null");
            return (Criteria) this;
        }

        public Criteria andSaleOrderNoIsNotNull() {
            addCriterion("SALE_ORDER_NO is not null");
            return (Criteria) this;
        }

        public Criteria andSaleOrderNoEqualTo(Long value) {
            addCriterion("SALE_ORDER_NO =", value, "saleOrderNo");
            return (Criteria) this;
        }

        public Criteria andSaleOrderNoNotEqualTo(Long value) {
            addCriterion("SALE_ORDER_NO <>", value, "saleOrderNo");
            return (Criteria) this;
        }

        public Criteria andSaleOrderNoGreaterThan(Long value) {
            addCriterion("SALE_ORDER_NO >", value, "saleOrderNo");
            return (Criteria) this;
        }

        public Criteria andSaleOrderNoGreaterThanOrEqualTo(Long value) {
            addCriterion("SALE_ORDER_NO >=", value, "saleOrderNo");
            return (Criteria) this;
        }

        public Criteria andSaleOrderNoLessThan(Long value) {
            addCriterion("SALE_ORDER_NO <", value, "saleOrderNo");
            return (Criteria) this;
        }

        public Criteria andSaleOrderNoLessThanOrEqualTo(Long value) {
            addCriterion("SALE_ORDER_NO <=", value, "saleOrderNo");
            return (Criteria) this;
        }

        public Criteria andSaleOrderNoIn(List<Long> values) {
            addCriterion("SALE_ORDER_NO in", values, "saleOrderNo");
            return (Criteria) this;
        }

        public Criteria andSaleOrderNoNotIn(List<Long> values) {
            addCriterion("SALE_ORDER_NO not in", values, "saleOrderNo");
            return (Criteria) this;
        }

        public Criteria andSaleOrderNoBetween(Long value1, Long value2) {
            addCriterion("SALE_ORDER_NO between", value1, value2, "saleOrderNo");
            return (Criteria) this;
        }

        public Criteria andSaleOrderNoNotBetween(Long value1, Long value2) {
            addCriterion("SALE_ORDER_NO not between", value1, value2, "saleOrderNo");
            return (Criteria) this;
        }

        public Criteria andCreateTimeIsNull() {
            addCriterion("CREATE_TIME is null");
            return (Criteria) this;
        }

        public Criteria andCreateTimeIsNotNull() {
            addCriterion("CREATE_TIME is not null");
            return (Criteria) this;
        }

        public Criteria andCreateTimeEqualTo(Date value) {
            addCriterion("CREATE_TIME =", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeNotEqualTo(Date value) {
            addCriterion("CREATE_TIME <>", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeGreaterThan(Date value) {
            addCriterion("CREATE_TIME >", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeGreaterThanOrEqualTo(Date value) {
            addCriterion("CREATE_TIME >=", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeLessThan(Date value) {
            addCriterion("CREATE_TIME <", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeLessThanOrEqualTo(Date value) {
            addCriterion("CREATE_TIME <=", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeIn(List<Date> values) {
            addCriterion("CREATE_TIME in", values, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeNotIn(List<Date> values) {
            addCriterion("CREATE_TIME not in", values, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeBetween(Date value1, Date value2) {
            addCriterion("CREATE_TIME between", value1, value2, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeNotBetween(Date value1, Date value2) {
            addCriterion("CREATE_TIME not between", value1, value2, "createTime");
            return (Criteria) this;
        }

        public Criteria andModifyTimeIsNull() {
            addCriterion("MODIFY_TIME is null");
            return (Criteria) this;
        }

        public Criteria andModifyTimeIsNotNull() {
            addCriterion("MODIFY_TIME is not null");
            return (Criteria) this;
        }

        public Criteria andModifyTimeEqualTo(Date value) {
            addCriterion("MODIFY_TIME =", value, "modifyTime");
            return (Criteria) this;
        }

        public Criteria andModifyTimeNotEqualTo(Date value) {
            addCriterion("MODIFY_TIME <>", value, "modifyTime");
            return (Criteria) this;
        }

        public Criteria andModifyTimeGreaterThan(Date value) {
            addCriterion("MODIFY_TIME >", value, "modifyTime");
            return (Criteria) this;
        }

        public Criteria andModifyTimeGreaterThanOrEqualTo(Date value) {
            addCriterion("MODIFY_TIME >=", value, "modifyTime");
            return (Criteria) this;
        }

        public Criteria andModifyTimeLessThan(Date value) {
            addCriterion("MODIFY_TIME <", value, "modifyTime");
            return (Criteria) this;
        }

        public Criteria andModifyTimeLessThanOrEqualTo(Date value) {
            addCriterion("MODIFY_TIME <=", value, "modifyTime");
            return (Criteria) this;
        }

        public Criteria andModifyTimeIn(List<Date> values) {
            addCriterion("MODIFY_TIME in", values, "modifyTime");
            return (Criteria) this;
        }

        public Criteria andModifyTimeNotIn(List<Date> values) {
            addCriterion("MODIFY_TIME not in", values, "modifyTime");
            return (Criteria) this;
        }

        public Criteria andModifyTimeBetween(Date value1, Date value2) {
            addCriterion("MODIFY_TIME between", value1, value2, "modifyTime");
            return (Criteria) this;
        }

        public Criteria andModifyTimeNotBetween(Date value1, Date value2) {
            addCriterion("MODIFY_TIME not between", value1, value2, "modifyTime");
            return (Criteria) this;
        }

        public Criteria andCreatorIsNull() {
            addCriterion("CREATOR is null");
            return (Criteria) this;
        }

        public Criteria andCreatorIsNotNull() {
            addCriterion("CREATOR is not null");
            return (Criteria) this;
        }

        public Criteria andCreatorEqualTo(String value) {
            addCriterion("CREATOR =", value, "creator");
            return (Criteria) this;
        }

        public Criteria andCreatorNotEqualTo(String value) {
            addCriterion("CREATOR <>", value, "creator");
            return (Criteria) this;
        }

        public Criteria andCreatorGreaterThan(String value) {
            addCriterion("CREATOR >", value, "creator");
            return (Criteria) this;
        }

        public Criteria andCreatorGreaterThanOrEqualTo(String value) {
            addCriterion("CREATOR >=", value, "creator");
            return (Criteria) this;
        }

        public Criteria andCreatorLessThan(String value) {
            addCriterion("CREATOR <", value, "creator");
            return (Criteria) this;
        }

        public Criteria andCreatorLessThanOrEqualTo(String value) {
            addCriterion("CREATOR <=", value, "creator");
            return (Criteria) this;
        }

        public Criteria andCreatorLike(String value) {
            addCriterion("CREATOR like", value, "creator");
            return (Criteria) this;
        }

        public Criteria andCreatorNotLike(String value) {
            addCriterion("CREATOR not like", value, "creator");
            return (Criteria) this;
        }

        public Criteria andCreatorIn(List<String> values) {
            addCriterion("CREATOR in", values, "creator");
            return (Criteria) this;
        }

        public Criteria andCreatorNotIn(List<String> values) {
            addCriterion("CREATOR not in", values, "creator");
            return (Criteria) this;
        }

        public Criteria andCreatorBetween(String value1, String value2) {
            addCriterion("CREATOR between", value1, value2, "creator");
            return (Criteria) this;
        }

        public Criteria andCreatorNotBetween(String value1, String value2) {
            addCriterion("CREATOR not between", value1, value2, "creator");
            return (Criteria) this;
        }

        public Criteria andModifierIsNull() {
            addCriterion("MODIFIER is null");
            return (Criteria) this;
        }

        public Criteria andModifierIsNotNull() {
            addCriterion("MODIFIER is not null");
            return (Criteria) this;
        }

        public Criteria andModifierEqualTo(String value) {
            addCriterion("MODIFIER =", value, "modifier");
            return (Criteria) this;
        }

        public Criteria andModifierNotEqualTo(String value) {
            addCriterion("MODIFIER <>", value, "modifier");
            return (Criteria) this;
        }

        public Criteria andModifierGreaterThan(String value) {
            addCriterion("MODIFIER >", value, "modifier");
            return (Criteria) this;
        }

        public Criteria andModifierGreaterThanOrEqualTo(String value) {
            addCriterion("MODIFIER >=", value, "modifier");
            return (Criteria) this;
        }

        public Criteria andModifierLessThan(String value) {
            addCriterion("MODIFIER <", value, "modifier");
            return (Criteria) this;
        }

        public Criteria andModifierLessThanOrEqualTo(String value) {
            addCriterion("MODIFIER <=", value, "modifier");
            return (Criteria) this;
        }

        public Criteria andModifierLike(String value) {
            addCriterion("MODIFIER like", value, "modifier");
            return (Criteria) this;
        }

        public Criteria andModifierNotLike(String value) {
            addCriterion("MODIFIER not like", value, "modifier");
            return (Criteria) this;
        }

        public Criteria andModifierIn(List<String> values) {
            addCriterion("MODIFIER in", values, "modifier");
            return (Criteria) this;
        }

        public Criteria andModifierNotIn(List<String> values) {
            addCriterion("MODIFIER not in", values, "modifier");
            return (Criteria) this;
        }

        public Criteria andModifierBetween(String value1, String value2) {
            addCriterion("MODIFIER between", value1, value2, "modifier");
            return (Criteria) this;
        }

        public Criteria andModifierNotBetween(String value1, String value2) {
            addCriterion("MODIFIER not between", value1, value2, "modifier");
            return (Criteria) this;
        }

        public Criteria andValidIsNull() {
            addCriterion("VALID is null");
            return (Criteria) this;
        }

        public Criteria andValidIsNotNull() {
            addCriterion("VALID is not null");
            return (Criteria) this;
        }

        public Criteria andValidEqualTo(Boolean value) {
            addCriterion("VALID =", value, "valid");
            return (Criteria) this;
        }

        public Criteria andValidNotEqualTo(Boolean value) {
            addCriterion("VALID <>", value, "valid");
            return (Criteria) this;
        }

        public Criteria andValidGreaterThan(Boolean value) {
            addCriterion("VALID >", value, "valid");
            return (Criteria) this;
        }

        public Criteria andValidGreaterThanOrEqualTo(Boolean value) {
            addCriterion("VALID >=", value, "valid");
            return (Criteria) this;
        }

        public Criteria andValidLessThan(Boolean value) {
            addCriterion("VALID <", value, "valid");
            return (Criteria) this;
        }

        public Criteria andValidLessThanOrEqualTo(Boolean value) {
            addCriterion("VALID <=", value, "valid");
            return (Criteria) this;
        }

        public Criteria andValidIn(List<Boolean> values) {
            addCriterion("VALID in", values, "valid");
            return (Criteria) this;
        }

        public Criteria andValidNotIn(List<Boolean> values) {
            addCriterion("VALID not in", values, "valid");
            return (Criteria) this;
        }

        public Criteria andValidBetween(Boolean value1, Boolean value2) {
            addCriterion("VALID between", value1, value2, "valid");
            return (Criteria) this;
        }

        public Criteria andValidNotBetween(Boolean value1, Boolean value2) {
            addCriterion("VALID not between", value1, value2, "valid");
            return (Criteria) this;
        }

        public Criteria andOwnerIsNull() {
            addCriterion("OWNER is null");
            return (Criteria) this;
        }

        public Criteria andOwnerIsNotNull() {
            addCriterion("OWNER is not null");
            return (Criteria) this;
        }

        public Criteria andOwnerEqualTo(Integer value) {
            addCriterion("OWNER =", value, "owner");
            return (Criteria) this;
        }

        public Criteria andOwnerNotEqualTo(Integer value) {
            addCriterion("OWNER <>", value, "owner");
            return (Criteria) this;
        }

        public Criteria andOwnerGreaterThan(Integer value) {
            addCriterion("OWNER >", value, "owner");
            return (Criteria) this;
        }

        public Criteria andOwnerGreaterThanOrEqualTo(Integer value) {
            addCriterion("OWNER >=", value, "owner");
            return (Criteria) this;
        }

        public Criteria andOwnerLessThan(Integer value) {
            addCriterion("OWNER <", value, "owner");
            return (Criteria) this;
        }

        public Criteria andOwnerLessThanOrEqualTo(Integer value) {
            addCriterion("OWNER <=", value, "owner");
            return (Criteria) this;
        }

        public Criteria andOwnerIn(List<Integer> values) {
            addCriterion("OWNER in", values, "owner");
            return (Criteria) this;
        }

        public Criteria andOwnerNotIn(List<Integer> values) {
            addCriterion("OWNER not in", values, "owner");
            return (Criteria) this;
        }

        public Criteria andOwnerBetween(Integer value1, Integer value2) {
            addCriterion("OWNER between", value1, value2, "owner");
            return (Criteria) this;
        }

        public Criteria andOwnerNotBetween(Integer value1, Integer value2) {
            addCriterion("OWNER not between", value1, value2, "owner");
            return (Criteria) this;
        }

        public Criteria andStatusIsNull() {
            addCriterion("STATUS is null");
            return (Criteria) this;
        }

        public Criteria andStatusIsNotNull() {
            addCriterion("STATUS is not null");
            return (Criteria) this;
        }

        public Criteria andStatusEqualTo(Integer value) {
            addCriterion("STATUS =", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusNotEqualTo(Integer value) {
            addCriterion("STATUS <>", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusGreaterThan(Integer value) {
            addCriterion("STATUS >", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusGreaterThanOrEqualTo(Integer value) {
            addCriterion("STATUS >=", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusLessThan(Integer value) {
            addCriterion("STATUS <", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusLessThanOrEqualTo(Integer value) {
            addCriterion("STATUS <=", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusIn(List<Integer> values) {
            addCriterion("STATUS in", values, "status");
            return (Criteria) this;
        }

        public Criteria andStatusNotIn(List<Integer> values) {
            addCriterion("STATUS not in", values, "status");
            return (Criteria) this;
        }

        public Criteria andStatusBetween(Integer value1, Integer value2) {
            addCriterion("STATUS between", value1, value2, "status");
            return (Criteria) this;
        }

        public Criteria andStatusNotBetween(Integer value1, Integer value2) {
            addCriterion("STATUS not between", value1, value2, "status");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table TRA_SALE_ORDER_DETAIL
     *
     * @mbggenerated do_not_delete_during_merge Mon Feb 27 15:21:11 CST 2017
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table TRA_SALE_ORDER_DETAIL
     *
     * @mbggenerated Mon Feb 27 15:21:11 CST 2017
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}