package com.tempus.gss.product.tra.api.entity;

import java.io.Serializable;
import java.util.Date;
import java.util.List;

import com.fasterxml.jackson.databind.annotation.JsonSerialize;
import com.tempus.gss.order.entity.SaleChange;
import com.tempus.gss.serializer.LongSerializer;

public class TraSaleChangeExt  implements Serializable {
    /**
	 * 
	 */
	private static final long serialVersionUID = 1L;

	/**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TRA_SALE_CHANGE_EXT.SALE_CHANGE_NO
     *
     * @mbggenerated Fri Feb 24 15:34:26 CST 2017
     */
    @JsonSerialize(using = LongSerializer.class)
    private Long saleChangeNo;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TRA_SALE_CHANGE_EXT.ID
     *
     * @mbggenerated Fri Feb 24 15:34:26 CST 2017
     */
    @JsonSerialize(using = LongSerializer.class)
    private Long id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TRA_SALE_CHANGE_EXT.OWNER
     *
     * @mbggenerated Fri Feb 24 15:34:26 CST 2017
     */
    private Integer owner;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TRA_SALE_CHANGE_EXT.REFUND_WAY
     *
     * @mbggenerated Fri Feb 24 15:34:26 CST 2017
     */
    private Integer refundWay;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TRA_SALE_CHANGE_EXT.MODIFIER
     *
     * @mbggenerated Fri Feb 24 15:34:26 CST 2017
     */
    private String modifier;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TRA_SALE_CHANGE_EXT.STATUS
     *
     * @mbggenerated Fri Feb 24 15:34:26 CST 2017
     */
    private String status;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TRA_SALE_CHANGE_EXT.MODIFY_TIME
     *
     * @mbggenerated Fri Feb 24 15:34:26 CST 2017
     */
    private Date modifyTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TRA_SALE_CHANGE_EXT.VALID
     *
     * @mbggenerated Fri Feb 24 15:34:26 CST 2017
     */
    private Byte valid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TRA_SALE_CHANGE_EXT.CREATE_TIME
     *
     * @mbggenerated Fri Feb 24 15:34:26 CST 2017
     */
    private Date createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TRA_SALE_CHANGE_EXT.CREATOR
     *
     * @mbggenerated Fri Feb 24 15:34:26 CST 2017
     */
    private String creator;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TRA_SALE_CHANGE_EXT.CHANGE_TYPE
     *
     * @mbggenerated Fri Feb 24 15:34:26 CST 2017
     */
    private Integer changeType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TRA_SALE_CHANGE_EXT.SALE_CHANGE_EXT_NO
     *
     * @mbggenerated Fri Feb 24 15:34:26 CST 2017
     */
    @JsonSerialize(using = LongSerializer.class)
    private Long saleChangeExtNo;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TRA_SALE_CHANGE_EXT.SALE_ORDER_NO
     *
     * @mbggenerated Fri Feb 24 15:34:26 CST 2017
     */
    @JsonSerialize(using = LongSerializer.class)
    private Long saleOrderNo;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TRA_SALE_CHANGE_EXT.BUY_CHANGE_NO
     *
     * @mbggenerated Fri Feb 24 15:34:26 CST 2017
     */
    @JsonSerialize(using = LongSerializer.class)
    private Long buyChangeNo;
    
    private SaleChange saleChange;
    
    private List<TraSaleChangeDetail> traSaleChangeDetailList;
    
    private TraSaleOrderExt traSaleOrderExt;
    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TRA_SALE_CHANGE_EXT.SALE_CHANGE_NO
     *
     * @return the value of TRA_SALE_CHANGE_EXT.SALE_CHANGE_NO
     *
     * @mbggenerated Fri Feb 24 15:34:26 CST 2017
     */
    public Long getSaleChangeNo() {
        return saleChangeNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TRA_SALE_CHANGE_EXT.SALE_CHANGE_NO
     *
     * @param saleChangeNo the value for TRA_SALE_CHANGE_EXT.SALE_CHANGE_NO
     *
     * @mbggenerated Fri Feb 24 15:34:26 CST 2017
     */
    public void setSaleChangeNo(Long saleChangeNo) {
        this.saleChangeNo = saleChangeNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TRA_SALE_CHANGE_EXT.ID
     *
     * @return the value of TRA_SALE_CHANGE_EXT.ID
     *
     * @mbggenerated Fri Feb 24 15:34:26 CST 2017
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TRA_SALE_CHANGE_EXT.ID
     *
     * @param id the value for TRA_SALE_CHANGE_EXT.ID
     *
     * @mbggenerated Fri Feb 24 15:34:26 CST 2017
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TRA_SALE_CHANGE_EXT.OWNER
     *
     * @return the value of TRA_SALE_CHANGE_EXT.OWNER
     *
     * @mbggenerated Fri Feb 24 15:34:26 CST 2017
     */
    public Integer getOwner() {
        return owner;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TRA_SALE_CHANGE_EXT.OWNER
     *
     * @param owner the value for TRA_SALE_CHANGE_EXT.OWNER
     *
     * @mbggenerated Fri Feb 24 15:34:26 CST 2017
     */
    public void setOwner(Integer owner) {
        this.owner = owner;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TRA_SALE_CHANGE_EXT.REFUND_WAY
     *
     * @return the value of TRA_SALE_CHANGE_EXT.REFUND_WAY
     *
     * @mbggenerated Fri Feb 24 15:34:26 CST 2017
     */
    public Integer getRefundWay() {
        return refundWay;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TRA_SALE_CHANGE_EXT.REFUND_WAY
     *
     * @param refundWay the value for TRA_SALE_CHANGE_EXT.REFUND_WAY
     *
     * @mbggenerated Fri Feb 24 15:34:26 CST 2017
     */
    public void setRefundWay(Integer refundWay) {
        this.refundWay = refundWay;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TRA_SALE_CHANGE_EXT.MODIFIER
     *
     * @return the value of TRA_SALE_CHANGE_EXT.MODIFIER
     *
     * @mbggenerated Fri Feb 24 15:34:26 CST 2017
     */
    public String getModifier() {
        return modifier;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TRA_SALE_CHANGE_EXT.MODIFIER
     *
     * @param modifier the value for TRA_SALE_CHANGE_EXT.MODIFIER
     *
     * @mbggenerated Fri Feb 24 15:34:26 CST 2017
     */
    public void setModifier(String modifier) {
        this.modifier = modifier == null ? null : modifier.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TRA_SALE_CHANGE_EXT.STATUS
     *
     * @return the value of TRA_SALE_CHANGE_EXT.STATUS
     *
     * @mbggenerated Fri Feb 24 15:34:26 CST 2017
     */
    public String getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TRA_SALE_CHANGE_EXT.STATUS
     *
     * @param status the value for TRA_SALE_CHANGE_EXT.STATUS
     *
     * @mbggenerated Fri Feb 24 15:34:26 CST 2017
     */
    public void setStatus(String status) {
        this.status = status == null ? null : status.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TRA_SALE_CHANGE_EXT.MODIFY_TIME
     *
     * @return the value of TRA_SALE_CHANGE_EXT.MODIFY_TIME
     *
     * @mbggenerated Fri Feb 24 15:34:26 CST 2017
     */
    public Date getModifyTime() {
        return modifyTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TRA_SALE_CHANGE_EXT.MODIFY_TIME
     *
     * @param modifyTime the value for TRA_SALE_CHANGE_EXT.MODIFY_TIME
     *
     * @mbggenerated Fri Feb 24 15:34:26 CST 2017
     */
    public void setModifyTime(Date modifyTime) {
        this.modifyTime = modifyTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TRA_SALE_CHANGE_EXT.VALID
     *
     * @return the value of TRA_SALE_CHANGE_EXT.VALID
     *
     * @mbggenerated Fri Feb 24 15:34:26 CST 2017
     */
    public Byte getValid() {
        return valid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TRA_SALE_CHANGE_EXT.VALID
     *
     * @param valid the value for TRA_SALE_CHANGE_EXT.VALID
     *
     * @mbggenerated Fri Feb 24 15:34:26 CST 2017
     */
    public void setValid(Byte valid) {
        this.valid = valid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TRA_SALE_CHANGE_EXT.CREATE_TIME
     *
     * @return the value of TRA_SALE_CHANGE_EXT.CREATE_TIME
     *
     * @mbggenerated Fri Feb 24 15:34:26 CST 2017
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TRA_SALE_CHANGE_EXT.CREATE_TIME
     *
     * @param createTime the value for TRA_SALE_CHANGE_EXT.CREATE_TIME
     *
     * @mbggenerated Fri Feb 24 15:34:26 CST 2017
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TRA_SALE_CHANGE_EXT.CREATOR
     *
     * @return the value of TRA_SALE_CHANGE_EXT.CREATOR
     *
     * @mbggenerated Fri Feb 24 15:34:26 CST 2017
     */
    public String getCreator() {
        return creator;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TRA_SALE_CHANGE_EXT.CREATOR
     *
     * @param creator the value for TRA_SALE_CHANGE_EXT.CREATOR
     *
     * @mbggenerated Fri Feb 24 15:34:26 CST 2017
     */
    public void setCreator(String creator) {
        this.creator = creator == null ? null : creator.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TRA_SALE_CHANGE_EXT.CHANGE_TYPE
     *
     * @return the value of TRA_SALE_CHANGE_EXT.CHANGE_TYPE
     *
     * @mbggenerated Fri Feb 24 15:34:26 CST 2017
     */
    public Integer getChangeType() {
        return changeType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TRA_SALE_CHANGE_EXT.CHANGE_TYPE
     *
     * @param changeType the value for TRA_SALE_CHANGE_EXT.CHANGE_TYPE
     *
     * @mbggenerated Fri Feb 24 15:34:26 CST 2017
     */
    public void setChangeType(Integer changeType) {
        this.changeType = changeType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TRA_SALE_CHANGE_EXT.SALE_CHANGE_EXT_NO
     *
     * @return the value of TRA_SALE_CHANGE_EXT.SALE_CHANGE_EXT_NO
     *
     * @mbggenerated Fri Feb 24 15:34:26 CST 2017
     */
    public Long getSaleChangeExtNo() {
        return saleChangeExtNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TRA_SALE_CHANGE_EXT.SALE_CHANGE_EXT_NO
     *
     * @param saleChangeExtNo the value for TRA_SALE_CHANGE_EXT.SALE_CHANGE_EXT_NO
     *
     * @mbggenerated Fri Feb 24 15:34:26 CST 2017
     */
    public void setSaleChangeExtNo(Long saleChangeExtNo) {
        this.saleChangeExtNo = saleChangeExtNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TRA_SALE_CHANGE_EXT.SALE_ORDER_NO
     *
     * @return the value of TRA_SALE_CHANGE_EXT.SALE_ORDER_NO
     *
     * @mbggenerated Fri Feb 24 15:34:26 CST 2017
     */
    public Long getSaleOrderNo() {
        return saleOrderNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TRA_SALE_CHANGE_EXT.SALE_ORDER_NO
     *
     * @param saleOrderNo the value for TRA_SALE_CHANGE_EXT.SALE_ORDER_NO
     *
     * @mbggenerated Fri Feb 24 15:34:26 CST 2017
     */
    public void setSaleOrderNo(Long saleOrderNo) {
        this.saleOrderNo = saleOrderNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TRA_SALE_CHANGE_EXT.BUY_CHANGE_NO
     *
     * @return the value of TRA_SALE_CHANGE_EXT.BUY_CHANGE_NO
     *
     * @mbggenerated Fri Feb 24 15:34:26 CST 2017
     */
    public Long getBuyChangeNo() {
        return buyChangeNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TRA_SALE_CHANGE_EXT.BUY_CHANGE_NO
     *
     * @param buyChangeNo the value for TRA_SALE_CHANGE_EXT.BUY_CHANGE_NO
     *
     * @mbggenerated Fri Feb 24 15:34:26 CST 2017
     */
    public void setBuyChangeNo(Long buyChangeNo) {
        this.buyChangeNo = buyChangeNo;
    }

	public SaleChange getSaleChange() {
		return saleChange;
	}

	public void setSaleChange(SaleChange saleChange) {
		this.saleChange = saleChange;
	}

	public List<TraSaleChangeDetail> getTraSaleChangeDetailList() {
		return traSaleChangeDetailList;
	}

	public void setTraSaleChangeDetailList(List<TraSaleChangeDetail> traSaleChangeDetailList) {
		this.traSaleChangeDetailList = traSaleChangeDetailList;
	}

	public TraSaleOrderExt getTraSaleOrderExt() {
		return traSaleOrderExt;
	}

	public void setTraSaleOrderExt(TraSaleOrderExt traSaleOrderExt) {
		this.traSaleOrderExt = traSaleOrderExt;
	}
    
	
}