package com.tempus.gss.product.tra.api.entity;

import java.util.ArrayList;
import java.util.Date;
import java.util.List;

public class TraSaleChangeExtExample   {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table TRA_SALE_CHANGE_EXT
     *
     * @mbggenerated Fri Feb 24 15:34:26 CST 2017
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table TRA_SALE_CHANGE_EXT
     *
     * @mbggenerated Fri Feb 24 15:34:26 CST 2017
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table TRA_SALE_CHANGE_EXT
     *
     * @mbggenerated Fri Feb 24 15:34:26 CST 2017
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TRA_SALE_CHANGE_EXT
     *
     * @mbggenerated Fri Feb 24 15:34:26 CST 2017
     */
    public TraSaleChangeExtExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TRA_SALE_CHANGE_EXT
     *
     * @mbggenerated Fri Feb 24 15:34:26 CST 2017
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TRA_SALE_CHANGE_EXT
     *
     * @mbggenerated Fri Feb 24 15:34:26 CST 2017
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TRA_SALE_CHANGE_EXT
     *
     * @mbggenerated Fri Feb 24 15:34:26 CST 2017
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TRA_SALE_CHANGE_EXT
     *
     * @mbggenerated Fri Feb 24 15:34:26 CST 2017
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TRA_SALE_CHANGE_EXT
     *
     * @mbggenerated Fri Feb 24 15:34:26 CST 2017
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TRA_SALE_CHANGE_EXT
     *
     * @mbggenerated Fri Feb 24 15:34:26 CST 2017
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TRA_SALE_CHANGE_EXT
     *
     * @mbggenerated Fri Feb 24 15:34:26 CST 2017
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TRA_SALE_CHANGE_EXT
     *
     * @mbggenerated Fri Feb 24 15:34:26 CST 2017
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TRA_SALE_CHANGE_EXT
     *
     * @mbggenerated Fri Feb 24 15:34:26 CST 2017
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TRA_SALE_CHANGE_EXT
     *
     * @mbggenerated Fri Feb 24 15:34:26 CST 2017
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table TRA_SALE_CHANGE_EXT
     *
     * @mbggenerated Fri Feb 24 15:34:26 CST 2017
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andSaleChangeNoIsNull() {
            addCriterion("SALE_CHANGE_NO is null");
            return (Criteria) this;
        }

        public Criteria andSaleChangeNoIsNotNull() {
            addCriterion("SALE_CHANGE_NO is not null");
            return (Criteria) this;
        }

        public Criteria andSaleChangeNoEqualTo(Long value) {
            addCriterion("SALE_CHANGE_NO =", value, "saleChangeNo");
            return (Criteria) this;
        }

        public Criteria andSaleChangeNoNotEqualTo(Long value) {
            addCriterion("SALE_CHANGE_NO <>", value, "saleChangeNo");
            return (Criteria) this;
        }

        public Criteria andSaleChangeNoGreaterThan(Long value) {
            addCriterion("SALE_CHANGE_NO >", value, "saleChangeNo");
            return (Criteria) this;
        }

        public Criteria andSaleChangeNoGreaterThanOrEqualTo(Long value) {
            addCriterion("SALE_CHANGE_NO >=", value, "saleChangeNo");
            return (Criteria) this;
        }

        public Criteria andSaleChangeNoLessThan(Long value) {
            addCriterion("SALE_CHANGE_NO <", value, "saleChangeNo");
            return (Criteria) this;
        }

        public Criteria andSaleChangeNoLessThanOrEqualTo(Long value) {
            addCriterion("SALE_CHANGE_NO <=", value, "saleChangeNo");
            return (Criteria) this;
        }

        public Criteria andSaleChangeNoIn(List<Long> values) {
            addCriterion("SALE_CHANGE_NO in", values, "saleChangeNo");
            return (Criteria) this;
        }

        public Criteria andSaleChangeNoNotIn(List<Long> values) {
            addCriterion("SALE_CHANGE_NO not in", values, "saleChangeNo");
            return (Criteria) this;
        }

        public Criteria andSaleChangeNoBetween(Long value1, Long value2) {
            addCriterion("SALE_CHANGE_NO between", value1, value2, "saleChangeNo");
            return (Criteria) this;
        }

        public Criteria andSaleChangeNoNotBetween(Long value1, Long value2) {
            addCriterion("SALE_CHANGE_NO not between", value1, value2, "saleChangeNo");
            return (Criteria) this;
        }

        public Criteria andIdIsNull() {
            addCriterion("ID is null");
            return (Criteria) this;
        }

        public Criteria andIdIsNotNull() {
            addCriterion("ID is not null");
            return (Criteria) this;
        }

        public Criteria andIdEqualTo(Long value) {
            addCriterion("ID =", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotEqualTo(Long value) {
            addCriterion("ID <>", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThan(Long value) {
            addCriterion("ID >", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThanOrEqualTo(Long value) {
            addCriterion("ID >=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThan(Long value) {
            addCriterion("ID <", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThanOrEqualTo(Long value) {
            addCriterion("ID <=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdIn(List<Long> values) {
            addCriterion("ID in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotIn(List<Long> values) {
            addCriterion("ID not in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdBetween(Long value1, Long value2) {
            addCriterion("ID between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotBetween(Long value1, Long value2) {
            addCriterion("ID not between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andOwnerIsNull() {
            addCriterion("OWNER is null");
            return (Criteria) this;
        }

        public Criteria andOwnerIsNotNull() {
            addCriterion("OWNER is not null");
            return (Criteria) this;
        }

        public Criteria andOwnerEqualTo(Integer value) {
            addCriterion("OWNER =", value, "owner");
            return (Criteria) this;
        }

        public Criteria andOwnerNotEqualTo(Integer value) {
            addCriterion("OWNER <>", value, "owner");
            return (Criteria) this;
        }

        public Criteria andOwnerGreaterThan(Integer value) {
            addCriterion("OWNER >", value, "owner");
            return (Criteria) this;
        }

        public Criteria andOwnerGreaterThanOrEqualTo(Integer value) {
            addCriterion("OWNER >=", value, "owner");
            return (Criteria) this;
        }

        public Criteria andOwnerLessThan(Integer value) {
            addCriterion("OWNER <", value, "owner");
            return (Criteria) this;
        }

        public Criteria andOwnerLessThanOrEqualTo(Integer value) {
            addCriterion("OWNER <=", value, "owner");
            return (Criteria) this;
        }

        public Criteria andOwnerIn(List<Integer> values) {
            addCriterion("OWNER in", values, "owner");
            return (Criteria) this;
        }

        public Criteria andOwnerNotIn(List<Integer> values) {
            addCriterion("OWNER not in", values, "owner");
            return (Criteria) this;
        }

        public Criteria andOwnerBetween(Integer value1, Integer value2) {
            addCriterion("OWNER between", value1, value2, "owner");
            return (Criteria) this;
        }

        public Criteria andOwnerNotBetween(Integer value1, Integer value2) {
            addCriterion("OWNER not between", value1, value2, "owner");
            return (Criteria) this;
        }

        public Criteria andRefundWayIsNull() {
            addCriterion("REFUND_WAY is null");
            return (Criteria) this;
        }

        public Criteria andRefundWayIsNotNull() {
            addCriterion("REFUND_WAY is not null");
            return (Criteria) this;
        }

        public Criteria andRefundWayEqualTo(Integer value) {
            addCriterion("REFUND_WAY =", value, "refundWay");
            return (Criteria) this;
        }

        public Criteria andRefundWayNotEqualTo(Integer value) {
            addCriterion("REFUND_WAY <>", value, "refundWay");
            return (Criteria) this;
        }

        public Criteria andRefundWayGreaterThan(Integer value) {
            addCriterion("REFUND_WAY >", value, "refundWay");
            return (Criteria) this;
        }

        public Criteria andRefundWayGreaterThanOrEqualTo(Integer value) {
            addCriterion("REFUND_WAY >=", value, "refundWay");
            return (Criteria) this;
        }

        public Criteria andRefundWayLessThan(Integer value) {
            addCriterion("REFUND_WAY <", value, "refundWay");
            return (Criteria) this;
        }

        public Criteria andRefundWayLessThanOrEqualTo(Integer value) {
            addCriterion("REFUND_WAY <=", value, "refundWay");
            return (Criteria) this;
        }

        public Criteria andRefundWayIn(List<Integer> values) {
            addCriterion("REFUND_WAY in", values, "refundWay");
            return (Criteria) this;
        }

        public Criteria andRefundWayNotIn(List<Integer> values) {
            addCriterion("REFUND_WAY not in", values, "refundWay");
            return (Criteria) this;
        }

        public Criteria andRefundWayBetween(Integer value1, Integer value2) {
            addCriterion("REFUND_WAY between", value1, value2, "refundWay");
            return (Criteria) this;
        }

        public Criteria andRefundWayNotBetween(Integer value1, Integer value2) {
            addCriterion("REFUND_WAY not between", value1, value2, "refundWay");
            return (Criteria) this;
        }

        public Criteria andModifierIsNull() {
            addCriterion("MODIFIER is null");
            return (Criteria) this;
        }

        public Criteria andModifierIsNotNull() {
            addCriterion("MODIFIER is not null");
            return (Criteria) this;
        }

        public Criteria andModifierEqualTo(String value) {
            addCriterion("MODIFIER =", value, "modifier");
            return (Criteria) this;
        }

        public Criteria andModifierNotEqualTo(String value) {
            addCriterion("MODIFIER <>", value, "modifier");
            return (Criteria) this;
        }

        public Criteria andModifierGreaterThan(String value) {
            addCriterion("MODIFIER >", value, "modifier");
            return (Criteria) this;
        }

        public Criteria andModifierGreaterThanOrEqualTo(String value) {
            addCriterion("MODIFIER >=", value, "modifier");
            return (Criteria) this;
        }

        public Criteria andModifierLessThan(String value) {
            addCriterion("MODIFIER <", value, "modifier");
            return (Criteria) this;
        }

        public Criteria andModifierLessThanOrEqualTo(String value) {
            addCriterion("MODIFIER <=", value, "modifier");
            return (Criteria) this;
        }

        public Criteria andModifierLike(String value) {
            addCriterion("MODIFIER like", value, "modifier");
            return (Criteria) this;
        }

        public Criteria andModifierNotLike(String value) {
            addCriterion("MODIFIER not like", value, "modifier");
            return (Criteria) this;
        }

        public Criteria andModifierIn(List<String> values) {
            addCriterion("MODIFIER in", values, "modifier");
            return (Criteria) this;
        }

        public Criteria andModifierNotIn(List<String> values) {
            addCriterion("MODIFIER not in", values, "modifier");
            return (Criteria) this;
        }

        public Criteria andModifierBetween(String value1, String value2) {
            addCriterion("MODIFIER between", value1, value2, "modifier");
            return (Criteria) this;
        }

        public Criteria andModifierNotBetween(String value1, String value2) {
            addCriterion("MODIFIER not between", value1, value2, "modifier");
            return (Criteria) this;
        }

        public Criteria andStatusIsNull() {
            addCriterion("STATUS is null");
            return (Criteria) this;
        }

        public Criteria andStatusIsNotNull() {
            addCriterion("STATUS is not null");
            return (Criteria) this;
        }

        public Criteria andStatusEqualTo(String value) {
            addCriterion("STATUS =", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusNotEqualTo(String value) {
            addCriterion("STATUS <>", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusGreaterThan(String value) {
            addCriterion("STATUS >", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusGreaterThanOrEqualTo(String value) {
            addCriterion("STATUS >=", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusLessThan(String value) {
            addCriterion("STATUS <", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusLessThanOrEqualTo(String value) {
            addCriterion("STATUS <=", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusLike(String value) {
            addCriterion("STATUS like", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusNotLike(String value) {
            addCriterion("STATUS not like", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusIn(List<String> values) {
            addCriterion("STATUS in", values, "status");
            return (Criteria) this;
        }

        public Criteria andStatusNotIn(List<String> values) {
            addCriterion("STATUS not in", values, "status");
            return (Criteria) this;
        }

        public Criteria andStatusBetween(String value1, String value2) {
            addCriterion("STATUS between", value1, value2, "status");
            return (Criteria) this;
        }

        public Criteria andStatusNotBetween(String value1, String value2) {
            addCriterion("STATUS not between", value1, value2, "status");
            return (Criteria) this;
        }

        public Criteria andModifyTimeIsNull() {
            addCriterion("MODIFY_TIME is null");
            return (Criteria) this;
        }

        public Criteria andModifyTimeIsNotNull() {
            addCriterion("MODIFY_TIME is not null");
            return (Criteria) this;
        }

        public Criteria andModifyTimeEqualTo(Date value) {
            addCriterion("MODIFY_TIME =", value, "modifyTime");
            return (Criteria) this;
        }

        public Criteria andModifyTimeNotEqualTo(Date value) {
            addCriterion("MODIFY_TIME <>", value, "modifyTime");
            return (Criteria) this;
        }

        public Criteria andModifyTimeGreaterThan(Date value) {
            addCriterion("MODIFY_TIME >", value, "modifyTime");
            return (Criteria) this;
        }

        public Criteria andModifyTimeGreaterThanOrEqualTo(Date value) {
            addCriterion("MODIFY_TIME >=", value, "modifyTime");
            return (Criteria) this;
        }

        public Criteria andModifyTimeLessThan(Date value) {
            addCriterion("MODIFY_TIME <", value, "modifyTime");
            return (Criteria) this;
        }

        public Criteria andModifyTimeLessThanOrEqualTo(Date value) {
            addCriterion("MODIFY_TIME <=", value, "modifyTime");
            return (Criteria) this;
        }

        public Criteria andModifyTimeIn(List<Date> values) {
            addCriterion("MODIFY_TIME in", values, "modifyTime");
            return (Criteria) this;
        }

        public Criteria andModifyTimeNotIn(List<Date> values) {
            addCriterion("MODIFY_TIME not in", values, "modifyTime");
            return (Criteria) this;
        }

        public Criteria andModifyTimeBetween(Date value1, Date value2) {
            addCriterion("MODIFY_TIME between", value1, value2, "modifyTime");
            return (Criteria) this;
        }

        public Criteria andModifyTimeNotBetween(Date value1, Date value2) {
            addCriterion("MODIFY_TIME not between", value1, value2, "modifyTime");
            return (Criteria) this;
        }

        public Criteria andValidIsNull() {
            addCriterion("VALID is null");
            return (Criteria) this;
        }

        public Criteria andValidIsNotNull() {
            addCriterion("VALID is not null");
            return (Criteria) this;
        }

        public Criteria andValidEqualTo(Byte value) {
            addCriterion("VALID =", value, "valid");
            return (Criteria) this;
        }

        public Criteria andValidNotEqualTo(Byte value) {
            addCriterion("VALID <>", value, "valid");
            return (Criteria) this;
        }

        public Criteria andValidGreaterThan(Byte value) {
            addCriterion("VALID >", value, "valid");
            return (Criteria) this;
        }

        public Criteria andValidGreaterThanOrEqualTo(Byte value) {
            addCriterion("VALID >=", value, "valid");
            return (Criteria) this;
        }

        public Criteria andValidLessThan(Byte value) {
            addCriterion("VALID <", value, "valid");
            return (Criteria) this;
        }

        public Criteria andValidLessThanOrEqualTo(Byte value) {
            addCriterion("VALID <=", value, "valid");
            return (Criteria) this;
        }

        public Criteria andValidIn(List<Byte> values) {
            addCriterion("VALID in", values, "valid");
            return (Criteria) this;
        }

        public Criteria andValidNotIn(List<Byte> values) {
            addCriterion("VALID not in", values, "valid");
            return (Criteria) this;
        }

        public Criteria andValidBetween(Byte value1, Byte value2) {
            addCriterion("VALID between", value1, value2, "valid");
            return (Criteria) this;
        }

        public Criteria andValidNotBetween(Byte value1, Byte value2) {
            addCriterion("VALID not between", value1, value2, "valid");
            return (Criteria) this;
        }

        public Criteria andCreateTimeIsNull() {
            addCriterion("CREATE_TIME is null");
            return (Criteria) this;
        }

        public Criteria andCreateTimeIsNotNull() {
            addCriterion("CREATE_TIME is not null");
            return (Criteria) this;
        }

        public Criteria andCreateTimeEqualTo(Date value) {
            addCriterion("CREATE_TIME =", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeNotEqualTo(Date value) {
            addCriterion("CREATE_TIME <>", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeGreaterThan(Date value) {
            addCriterion("CREATE_TIME >", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeGreaterThanOrEqualTo(Date value) {
            addCriterion("CREATE_TIME >=", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeLessThan(Date value) {
            addCriterion("CREATE_TIME <", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeLessThanOrEqualTo(Date value) {
            addCriterion("CREATE_TIME <=", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeIn(List<Date> values) {
            addCriterion("CREATE_TIME in", values, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeNotIn(List<Date> values) {
            addCriterion("CREATE_TIME not in", values, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeBetween(Date value1, Date value2) {
            addCriterion("CREATE_TIME between", value1, value2, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeNotBetween(Date value1, Date value2) {
            addCriterion("CREATE_TIME not between", value1, value2, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreatorIsNull() {
            addCriterion("CREATOR is null");
            return (Criteria) this;
        }

        public Criteria andCreatorIsNotNull() {
            addCriterion("CREATOR is not null");
            return (Criteria) this;
        }

        public Criteria andCreatorEqualTo(String value) {
            addCriterion("CREATOR =", value, "creator");
            return (Criteria) this;
        }

        public Criteria andCreatorNotEqualTo(String value) {
            addCriterion("CREATOR <>", value, "creator");
            return (Criteria) this;
        }

        public Criteria andCreatorGreaterThan(String value) {
            addCriterion("CREATOR >", value, "creator");
            return (Criteria) this;
        }

        public Criteria andCreatorGreaterThanOrEqualTo(String value) {
            addCriterion("CREATOR >=", value, "creator");
            return (Criteria) this;
        }

        public Criteria andCreatorLessThan(String value) {
            addCriterion("CREATOR <", value, "creator");
            return (Criteria) this;
        }

        public Criteria andCreatorLessThanOrEqualTo(String value) {
            addCriterion("CREATOR <=", value, "creator");
            return (Criteria) this;
        }

        public Criteria andCreatorLike(String value) {
            addCriterion("CREATOR like", value, "creator");
            return (Criteria) this;
        }

        public Criteria andCreatorNotLike(String value) {
            addCriterion("CREATOR not like", value, "creator");
            return (Criteria) this;
        }

        public Criteria andCreatorIn(List<String> values) {
            addCriterion("CREATOR in", values, "creator");
            return (Criteria) this;
        }

        public Criteria andCreatorNotIn(List<String> values) {
            addCriterion("CREATOR not in", values, "creator");
            return (Criteria) this;
        }

        public Criteria andCreatorBetween(String value1, String value2) {
            addCriterion("CREATOR between", value1, value2, "creator");
            return (Criteria) this;
        }

        public Criteria andCreatorNotBetween(String value1, String value2) {
            addCriterion("CREATOR not between", value1, value2, "creator");
            return (Criteria) this;
        }

        public Criteria andChangeTypeIsNull() {
            addCriterion("CHANGE_TYPE is null");
            return (Criteria) this;
        }

        public Criteria andChangeTypeIsNotNull() {
            addCriterion("CHANGE_TYPE is not null");
            return (Criteria) this;
        }

        public Criteria andChangeTypeEqualTo(Integer value) {
            addCriterion("CHANGE_TYPE =", value, "changeType");
            return (Criteria) this;
        }

        public Criteria andChangeTypeNotEqualTo(Integer value) {
            addCriterion("CHANGE_TYPE <>", value, "changeType");
            return (Criteria) this;
        }

        public Criteria andChangeTypeGreaterThan(Integer value) {
            addCriterion("CHANGE_TYPE >", value, "changeType");
            return (Criteria) this;
        }

        public Criteria andChangeTypeGreaterThanOrEqualTo(Integer value) {
            addCriterion("CHANGE_TYPE >=", value, "changeType");
            return (Criteria) this;
        }

        public Criteria andChangeTypeLessThan(Integer value) {
            addCriterion("CHANGE_TYPE <", value, "changeType");
            return (Criteria) this;
        }

        public Criteria andChangeTypeLessThanOrEqualTo(Integer value) {
            addCriterion("CHANGE_TYPE <=", value, "changeType");
            return (Criteria) this;
        }

        public Criteria andChangeTypeIn(List<Integer> values) {
            addCriterion("CHANGE_TYPE in", values, "changeType");
            return (Criteria) this;
        }

        public Criteria andChangeTypeNotIn(List<Integer> values) {
            addCriterion("CHANGE_TYPE not in", values, "changeType");
            return (Criteria) this;
        }

        public Criteria andChangeTypeBetween(Integer value1, Integer value2) {
            addCriterion("CHANGE_TYPE between", value1, value2, "changeType");
            return (Criteria) this;
        }

        public Criteria andChangeTypeNotBetween(Integer value1, Integer value2) {
            addCriterion("CHANGE_TYPE not between", value1, value2, "changeType");
            return (Criteria) this;
        }

        public Criteria andSaleChangeExtNoIsNull() {
            addCriterion("SALE_CHANGE_EXT_NO is null");
            return (Criteria) this;
        }

        public Criteria andSaleChangeExtNoIsNotNull() {
            addCriterion("SALE_CHANGE_EXT_NO is not null");
            return (Criteria) this;
        }

        public Criteria andSaleChangeExtNoEqualTo(Long value) {
            addCriterion("SALE_CHANGE_EXT_NO =", value, "saleChangeExtNo");
            return (Criteria) this;
        }

        public Criteria andSaleChangeExtNoNotEqualTo(Long value) {
            addCriterion("SALE_CHANGE_EXT_NO <>", value, "saleChangeExtNo");
            return (Criteria) this;
        }

        public Criteria andSaleChangeExtNoGreaterThan(Long value) {
            addCriterion("SALE_CHANGE_EXT_NO >", value, "saleChangeExtNo");
            return (Criteria) this;
        }

        public Criteria andSaleChangeExtNoGreaterThanOrEqualTo(Long value) {
            addCriterion("SALE_CHANGE_EXT_NO >=", value, "saleChangeExtNo");
            return (Criteria) this;
        }

        public Criteria andSaleChangeExtNoLessThan(Long value) {
            addCriterion("SALE_CHANGE_EXT_NO <", value, "saleChangeExtNo");
            return (Criteria) this;
        }

        public Criteria andSaleChangeExtNoLessThanOrEqualTo(Long value) {
            addCriterion("SALE_CHANGE_EXT_NO <=", value, "saleChangeExtNo");
            return (Criteria) this;
        }

        public Criteria andSaleChangeExtNoIn(List<Long> values) {
            addCriterion("SALE_CHANGE_EXT_NO in", values, "saleChangeExtNo");
            return (Criteria) this;
        }

        public Criteria andSaleChangeExtNoNotIn(List<Long> values) {
            addCriterion("SALE_CHANGE_EXT_NO not in", values, "saleChangeExtNo");
            return (Criteria) this;
        }

        public Criteria andSaleChangeExtNoBetween(Long value1, Long value2) {
            addCriterion("SALE_CHANGE_EXT_NO between", value1, value2, "saleChangeExtNo");
            return (Criteria) this;
        }

        public Criteria andSaleChangeExtNoNotBetween(Long value1, Long value2) {
            addCriterion("SALE_CHANGE_EXT_NO not between", value1, value2, "saleChangeExtNo");
            return (Criteria) this;
        }

        public Criteria andSaleOrderNoIsNull() {
            addCriterion("SALE_ORDER_NO is null");
            return (Criteria) this;
        }

        public Criteria andSaleOrderNoIsNotNull() {
            addCriterion("SALE_ORDER_NO is not null");
            return (Criteria) this;
        }

        public Criteria andSaleOrderNoEqualTo(Long value) {
            addCriterion("SALE_ORDER_NO =", value, "saleOrderNo");
            return (Criteria) this;
        }

        public Criteria andSaleOrderNoNotEqualTo(Long value) {
            addCriterion("SALE_ORDER_NO <>", value, "saleOrderNo");
            return (Criteria) this;
        }

        public Criteria andSaleOrderNoGreaterThan(Long value) {
            addCriterion("SALE_ORDER_NO >", value, "saleOrderNo");
            return (Criteria) this;
        }

        public Criteria andSaleOrderNoGreaterThanOrEqualTo(Long value) {
            addCriterion("SALE_ORDER_NO >=", value, "saleOrderNo");
            return (Criteria) this;
        }

        public Criteria andSaleOrderNoLessThan(Long value) {
            addCriterion("SALE_ORDER_NO <", value, "saleOrderNo");
            return (Criteria) this;
        }

        public Criteria andSaleOrderNoLessThanOrEqualTo(Long value) {
            addCriterion("SALE_ORDER_NO <=", value, "saleOrderNo");
            return (Criteria) this;
        }

        public Criteria andSaleOrderNoIn(List<Long> values) {
            addCriterion("SALE_ORDER_NO in", values, "saleOrderNo");
            return (Criteria) this;
        }

        public Criteria andSaleOrderNoNotIn(List<Long> values) {
            addCriterion("SALE_ORDER_NO not in", values, "saleOrderNo");
            return (Criteria) this;
        }

        public Criteria andSaleOrderNoBetween(Long value1, Long value2) {
            addCriterion("SALE_ORDER_NO between", value1, value2, "saleOrderNo");
            return (Criteria) this;
        }

        public Criteria andSaleOrderNoNotBetween(Long value1, Long value2) {
            addCriterion("SALE_ORDER_NO not between", value1, value2, "saleOrderNo");
            return (Criteria) this;
        }

        public Criteria andBuyChangeNoIsNull() {
            addCriterion("BUY_CHANGE_NO is null");
            return (Criteria) this;
        }

        public Criteria andBuyChangeNoIsNotNull() {
            addCriterion("BUY_CHANGE_NO is not null");
            return (Criteria) this;
        }

        public Criteria andBuyChangeNoEqualTo(Long value) {
            addCriterion("BUY_CHANGE_NO =", value, "buyChangeNo");
            return (Criteria) this;
        }

        public Criteria andBuyChangeNoNotEqualTo(Long value) {
            addCriterion("BUY_CHANGE_NO <>", value, "buyChangeNo");
            return (Criteria) this;
        }

        public Criteria andBuyChangeNoGreaterThan(Long value) {
            addCriterion("BUY_CHANGE_NO >", value, "buyChangeNo");
            return (Criteria) this;
        }

        public Criteria andBuyChangeNoGreaterThanOrEqualTo(Long value) {
            addCriterion("BUY_CHANGE_NO >=", value, "buyChangeNo");
            return (Criteria) this;
        }

        public Criteria andBuyChangeNoLessThan(Long value) {
            addCriterion("BUY_CHANGE_NO <", value, "buyChangeNo");
            return (Criteria) this;
        }

        public Criteria andBuyChangeNoLessThanOrEqualTo(Long value) {
            addCriterion("BUY_CHANGE_NO <=", value, "buyChangeNo");
            return (Criteria) this;
        }

        public Criteria andBuyChangeNoIn(List<Long> values) {
            addCriterion("BUY_CHANGE_NO in", values, "buyChangeNo");
            return (Criteria) this;
        }

        public Criteria andBuyChangeNoNotIn(List<Long> values) {
            addCriterion("BUY_CHANGE_NO not in", values, "buyChangeNo");
            return (Criteria) this;
        }

        public Criteria andBuyChangeNoBetween(Long value1, Long value2) {
            addCriterion("BUY_CHANGE_NO between", value1, value2, "buyChangeNo");
            return (Criteria) this;
        }

        public Criteria andBuyChangeNoNotBetween(Long value1, Long value2) {
            addCriterion("BUY_CHANGE_NO not between", value1, value2, "buyChangeNo");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table TRA_SALE_CHANGE_EXT
     *
     * @mbggenerated do_not_delete_during_merge Fri Feb 24 15:34:26 CST 2017
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table TRA_SALE_CHANGE_EXT
     *
     * @mbggenerated Fri Feb 24 15:34:26 CST 2017
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}