package com.tempus.gss.product.tra.api.entity.vo;

import java.io.Serializable;
import java.util.Date;

import com.fasterxml.jackson.databind.annotation.JsonSerialize;
import com.tempus.gss.serializer.LongSerializer;

public class TraSaleChangeExtVo  implements Serializable {
    /**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	
	@JsonSerialize(using = LongSerializer.class)
    private Long id;

	/**
     *
     */
    private Long saleChangeNo;

    /**
     *
     */
    private Integer owner;

    /**
     *
     */
    private Integer refundWay;

    /**
     *
     */
    private String modifier;

    /**
     *
     */
    private String status;

    /**
     *
     */
    private Date modifyTime;

    /**
     *
     */
    private Byte valid;

    /**
     *
     */
    private Date createTime;

    /**
     *
     */
    private String creator;

    /**
     *
     */
    private Integer changeType;

    /**
     *
     */
    private Long saleChangeExtNo;

    /**
     *
     */
    private Long saleOrderNo;

    /**
     *
     */
    private Long buyChangeNo;
    
    /**
     * 客商类型
     */
    private Long customerNo;
    
    /**
     * 客商编号
     */
    private Long customerTypeNo;

    /**
     *
     *
     */
    public Long getSaleChangeNo() {
        return saleChangeNo;
    }

    /**
     *
     *
     */
    public void setSaleChangeNo(Long saleChangeNo) {
        this.saleChangeNo = saleChangeNo;
    }


    /**
     *
     *
     */
    public Integer getOwner() {
        return owner;
    }

    /**
     *
     *
     */
    public void setOwner(Integer owner) {
        this.owner = owner;
    }

    /**
     *
     *
     */
    public Integer getRefundWay() {
        return refundWay;
    }

    /**
     *
     *
     */
    public void setRefundWay(Integer refundWay) {
        this.refundWay = refundWay;
    }

    /**
     *
     */
    public String getModifier() {
        return modifier;
    }

    /**
     *
     */
    public void setModifier(String modifier) {
        this.modifier = modifier == null ? null : modifier.trim();
    }

    /**
     *
     */
    public String getStatus() {
        return status;
    }

    /**
     *
     */
    public void setStatus(String status) {
        this.status = status == null ? null : status.trim();
    }

    /**
     *
     */
    public Date getModifyTime() {
        return modifyTime;
    }

    /**
     *
     */
    public void setModifyTime(Date modifyTime) {
        this.modifyTime = modifyTime;
    }

    /**
     *
     */
    public Byte getValid() {
        return valid;
    }

    /**
     *
     */
    public void setValid(Byte valid) {
        this.valid = valid;
    }

    /**
     *
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     *
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     *
     */
    public String getCreator() {
        return creator;
    }

    /**
     *
     */
    public void setCreator(String creator) {
        this.creator = creator == null ? null : creator.trim();
    }

    /**
     *
     */
    public Integer getChangeType() {
        return changeType;
    }

    /**
     *
     */
    public void setChangeType(Integer changeType) {
        this.changeType = changeType;
    }

    /**
     *
     */
    public Long getSaleChangeExtNo() {
        return saleChangeExtNo;
    }

    /**
     *
     */
    public void setSaleChangeExtNo(Long saleChangeExtNo) {
        this.saleChangeExtNo = saleChangeExtNo;
    }

    /**
     *
     */
    public Long getSaleOrderNo() {
        return saleOrderNo;
    }

    /**
     *
     */
    public void setSaleOrderNo(Long saleOrderNo) {
        this.saleOrderNo = saleOrderNo;
    }

    /**
     * This method was generated by MyBd.BUY_CHANGE_NO
     *
     */
    public Long getBuyChangeNo() {
        return buyChangeNo;
    }

    /**
     *
     */
    public void setBuyChangeNo(Long buyChangeNo) {
        this.buyChangeNo = buyChangeNo;
    }

	public Long getId() {
		return id;
	}

	public void setId(Long id) {
		this.id = id;
	}

	public Long getCustomerNo() {
		return customerNo;
	}

	public void setCustomerNo(Long customerNo) {
		this.customerNo = customerNo;
	}

	public Long getCustomerTypeNo() {
		return customerTypeNo;
	}

	public void setCustomerTypeNo(Long customerTypeNo) {
		this.customerTypeNo = customerTypeNo;
	}
    
    
}